package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ActivityFeed generated by hbm2java
 */
@Entity
@Table(name="activity_feed"
    ,catalog="villaeducativa"
)
public class ActivityFeed  implements java.io.Serializable {


     private Integer id;
     private int initiatorId;
     private int activityType;
     private Integer goalId;
     private String goalName;
     private String fieldName;
     private String initialFieldValue;
     private String newFieldValue;
     private Date activityTime;

    public ActivityFeed() {
    }

	
    public ActivityFeed(int initiatorId, int activityType, Date activityTime) {
        this.initiatorId = initiatorId;
        this.activityType = activityType;
        this.activityTime = activityTime;
    }
    public ActivityFeed(int initiatorId, int activityType, Integer goalId, String goalName, String fieldName, String initialFieldValue, String newFieldValue, Date activityTime) {
       this.initiatorId = initiatorId;
       this.activityType = activityType;
       this.goalId = goalId;
       this.goalName = goalName;
       this.fieldName = fieldName;
       this.initialFieldValue = initialFieldValue;
       this.newFieldValue = newFieldValue;
       this.activityTime = activityTime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="initiator_id", nullable=false)
    public int getInitiatorId() {
        return this.initiatorId;
    }
    
    public void setInitiatorId(int initiatorId) {
        this.initiatorId = initiatorId;
    }

    
    @Column(name="activity_type", nullable=false)
    public int getActivityType() {
        return this.activityType;
    }
    
    public void setActivityType(int activityType) {
        this.activityType = activityType;
    }

    
    @Column(name="goal_id")
    public Integer getGoalId() {
        return this.goalId;
    }
    
    public void setGoalId(Integer goalId) {
        this.goalId = goalId;
    }

    
    @Column(name="goal_name", length=120)
    public String getGoalName() {
        return this.goalName;
    }
    
    public void setGoalName(String goalName) {
        this.goalName = goalName;
    }

    
    @Column(name="field_name", length=120)
    public String getFieldName() {
        return this.fieldName;
    }
    
    public void setFieldName(String fieldName) {
        this.fieldName = fieldName;
    }

    
    @Column(name="initial_field_value", length=120)
    public String getInitialFieldValue() {
        return this.initialFieldValue;
    }
    
    public void setInitialFieldValue(String initialFieldValue) {
        this.initialFieldValue = initialFieldValue;
    }

    
    @Column(name="new_field_value", length=120)
    public String getNewFieldValue() {
        return this.newFieldValue;
    }
    
    public void setNewFieldValue(String newFieldValue) {
        this.newFieldValue = newFieldValue;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="activity_time", nullable=false, length=19)
    public Date getActivityTime() {
        return this.activityTime;
    }
    
    public void setActivityTime(Date activityTime) {
        this.activityTime = activityTime;
    }




}


