package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ActivityType generated by hbm2java
 */
@Entity
@Table(name="activity_type"
    ,catalog="villaeducativa"
)
public class ActivityType  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String text;
     private String colorCode;

    public ActivityType() {
    }

    public ActivityType(String name, String text, String colorCode) {
       this.name = name;
       this.text = text;
       this.colorCode = colorCode;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=120)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="text", nullable=false, length=120)
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }

    
    @Column(name="color_code", nullable=false, length=120)
    public String getColorCode() {
        return this.colorCode;
    }
    
    public void setColorCode(String colorCode) {
        this.colorCode = colorCode;
    }




}


