package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AdditionalExams generated by hbm2java
 */
@Entity
@Table(name="additional_exams"
    ,catalog="villaeducativa"
)
public class AdditionalExams  implements java.io.Serializable {


     private Integer id;
     private Integer additionalExamGroupId;
     private Integer subjectId;
     private Date startTime;
     private Date endTime;
     private Integer maximumMarks;
     private Integer minimumMarks;
     private Integer gradingLevelId;
     private Integer weightage;
     private Integer eventId;
     private Date createdAt;
     private Date updatedAt;

    public AdditionalExams() {
    }

    public AdditionalExams(Integer additionalExamGroupId, Integer subjectId, Date startTime, Date endTime, Integer maximumMarks, Integer minimumMarks, Integer gradingLevelId, Integer weightage, Integer eventId, Date createdAt, Date updatedAt) {
       this.additionalExamGroupId = additionalExamGroupId;
       this.subjectId = subjectId;
       this.startTime = startTime;
       this.endTime = endTime;
       this.maximumMarks = maximumMarks;
       this.minimumMarks = minimumMarks;
       this.gradingLevelId = gradingLevelId;
       this.weightage = weightage;
       this.eventId = eventId;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="additional_exam_group_id")
    public Integer getAdditionalExamGroupId() {
        return this.additionalExamGroupId;
    }
    
    public void setAdditionalExamGroupId(Integer additionalExamGroupId) {
        this.additionalExamGroupId = additionalExamGroupId;
    }

    
    @Column(name="subject_id")
    public Integer getSubjectId() {
        return this.subjectId;
    }
    
    public void setSubjectId(Integer subjectId) {
        this.subjectId = subjectId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="start_time", length=19)
    public Date getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="end_time", length=19)
    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    
    @Column(name="maximum_marks")
    public Integer getMaximumMarks() {
        return this.maximumMarks;
    }
    
    public void setMaximumMarks(Integer maximumMarks) {
        this.maximumMarks = maximumMarks;
    }

    
    @Column(name="minimum_marks")
    public Integer getMinimumMarks() {
        return this.minimumMarks;
    }
    
    public void setMinimumMarks(Integer minimumMarks) {
        this.minimumMarks = minimumMarks;
    }

    
    @Column(name="grading_level_id")
    public Integer getGradingLevelId() {
        return this.gradingLevelId;
    }
    
    public void setGradingLevelId(Integer gradingLevelId) {
        this.gradingLevelId = gradingLevelId;
    }

    
    @Column(name="weightage")
    public Integer getWeightage() {
        return this.weightage;
    }
    
    public void setWeightage(Integer weightage) {
        this.weightage = weightage;
    }

    
    @Column(name="event_id")
    public Integer getEventId() {
        return this.eventId;
    }
    
    public void setEventId(Integer eventId) {
        this.eventId = eventId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", length=19)
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at", length=19)
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }




}


