package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AdditionalExamScores generated by hbm2java
 */
@Entity
@Table(name="additional_exam_scores"
    ,catalog="villaeducativa"
)
public class AdditionalExamScores  implements java.io.Serializable {


     private Integer id;
     private Integer studentId;
     private Integer additionalExamId;
     private BigDecimal marks;
     private Integer gradingLevelId;
     private String remarks;
     private Boolean isFailed;
     private Date createdAt;
     private Date updatedAt;

    public AdditionalExamScores() {
    }

    public AdditionalExamScores(Integer studentId, Integer additionalExamId, BigDecimal marks, Integer gradingLevelId, String remarks, Boolean isFailed, Date createdAt, Date updatedAt) {
       this.studentId = studentId;
       this.additionalExamId = additionalExamId;
       this.marks = marks;
       this.gradingLevelId = gradingLevelId;
       this.remarks = remarks;
       this.isFailed = isFailed;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="student_id")
    public Integer getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    
    @Column(name="additional_exam_id")
    public Integer getAdditionalExamId() {
        return this.additionalExamId;
    }
    
    public void setAdditionalExamId(Integer additionalExamId) {
        this.additionalExamId = additionalExamId;
    }

    
    @Column(name="marks", precision=7)
    public BigDecimal getMarks() {
        return this.marks;
    }
    
    public void setMarks(BigDecimal marks) {
        this.marks = marks;
    }

    
    @Column(name="grading_level_id")
    public Integer getGradingLevelId() {
        return this.gradingLevelId;
    }
    
    public void setGradingLevelId(Integer gradingLevelId) {
        this.gradingLevelId = gradingLevelId;
    }

    
    @Column(name="remarks")
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    
    @Column(name="is_failed")
    public Boolean getIsFailed() {
        return this.isFailed;
    }
    
    public void setIsFailed(Boolean isFailed) {
        this.isFailed = isFailed;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", length=19)
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at", length=19)
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }




}


