package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Allotment generated by hbm2java
 */
@Entity
@Table(name="allotment"
    ,catalog="villaeducativa"
)
public class Allotment  implements java.io.Serializable {


     private Integer id;
     private String studentId;
     private String bedNo;
     private String roomNo;
     private String floor;
     private String status;
     private Date created;

    public Allotment() {
    }

    public Allotment(String studentId, String bedNo, String roomNo, String floor, String status, Date created) {
       this.studentId = studentId;
       this.bedNo = bedNo;
       this.roomNo = roomNo;
       this.floor = floor;
       this.status = status;
       this.created = created;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="student_id", length=120)
    public String getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(String studentId) {
        this.studentId = studentId;
    }

    
    @Column(name="bed_no", length=120)
    public String getBedNo() {
        return this.bedNo;
    }
    
    public void setBedNo(String bedNo) {
        this.bedNo = bedNo;
    }

    
    @Column(name="room_no", length=120)
    public String getRoomNo() {
        return this.roomNo;
    }
    
    public void setRoomNo(String roomNo) {
        this.roomNo = roomNo;
    }

    
    @Column(name="floor", length=120)
    public String getFloor() {
        return this.floor;
    }
    
    public void setFloor(String floor) {
        this.floor = floor;
    }

    
    @Column(name="status", length=120)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="created", length=10)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }




}


