package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ApplyLeaves generated by hbm2java
 */
@Entity
@Table(name="apply_leaves"
    ,catalog="villaeducativa"
)
public class ApplyLeaves  implements java.io.Serializable {


     private Integer id;
     private Integer employeeId;
     private Integer employeeLeaveTypesId;
     private Boolean isHalfDay;
     private Date startDate;
     private Date endDate;
     private String reason;
     private Boolean approved;
     private Boolean viewedByManager;
     private String managerRemark;

    public ApplyLeaves() {
    }

    public ApplyLeaves(Integer employeeId, Integer employeeLeaveTypesId, Boolean isHalfDay, Date startDate, Date endDate, String reason, Boolean approved, Boolean viewedByManager, String managerRemark) {
       this.employeeId = employeeId;
       this.employeeLeaveTypesId = employeeLeaveTypesId;
       this.isHalfDay = isHalfDay;
       this.startDate = startDate;
       this.endDate = endDate;
       this.reason = reason;
       this.approved = approved;
       this.viewedByManager = viewedByManager;
       this.managerRemark = managerRemark;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="employee_id")
    public Integer getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    
    @Column(name="employee_leave_types_id")
    public Integer getEmployeeLeaveTypesId() {
        return this.employeeLeaveTypesId;
    }
    
    public void setEmployeeLeaveTypesId(Integer employeeLeaveTypesId) {
        this.employeeLeaveTypesId = employeeLeaveTypesId;
    }

    
    @Column(name="is_half_day")
    public Boolean getIsHalfDay() {
        return this.isHalfDay;
    }
    
    public void setIsHalfDay(Boolean isHalfDay) {
        this.isHalfDay = isHalfDay;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="start_date", length=10)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="end_date", length=10)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    
    @Column(name="reason")
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }

    
    @Column(name="approved")
    public Boolean getApproved() {
        return this.approved;
    }
    
    public void setApproved(Boolean approved) {
        this.approved = approved;
    }

    
    @Column(name="viewed_by_manager")
    public Boolean getViewedByManager() {
        return this.viewedByManager;
    }
    
    public void setViewedByManager(Boolean viewedByManager) {
        this.viewedByManager = viewedByManager;
    }

    
    @Column(name="manager_remark")
    public String getManagerRemark() {
        return this.managerRemark;
    }
    
    public void setManagerRemark(String managerRemark) {
        this.managerRemark = managerRemark;
    }




}


