package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ArchivedGuardians generated by hbm2java
 */
@Entity
@Table(name="archived_guardians"
    ,catalog="villaeducativa"
)
public class ArchivedGuardians  implements java.io.Serializable {


     private Integer id;
     private Integer wardId;
     private String firstName;
     private String lastName;
     private String relation;
     private String email;
     private String officePhone1;
     private String officePhone2;
     private String mobilePhone;
     private String officeAddressLine1;
     private String officeAddressLine2;
     private String city;
     private String state;
     private Integer countryId;
     private Date dob;
     private String occupation;
     private String income;
     private String education;
     private Date createdAt;
     private Date updatedAt;

    public ArchivedGuardians() {
    }

    public ArchivedGuardians(Integer wardId, String firstName, String lastName, String relation, String email, String officePhone1, String officePhone2, String mobilePhone, String officeAddressLine1, String officeAddressLine2, String city, String state, Integer countryId, Date dob, String occupation, String income, String education, Date createdAt, Date updatedAt) {
       this.wardId = wardId;
       this.firstName = firstName;
       this.lastName = lastName;
       this.relation = relation;
       this.email = email;
       this.officePhone1 = officePhone1;
       this.officePhone2 = officePhone2;
       this.mobilePhone = mobilePhone;
       this.officeAddressLine1 = officeAddressLine1;
       this.officeAddressLine2 = officeAddressLine2;
       this.city = city;
       this.state = state;
       this.countryId = countryId;
       this.dob = dob;
       this.occupation = occupation;
       this.income = income;
       this.education = education;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="ward_id")
    public Integer getWardId() {
        return this.wardId;
    }
    
    public void setWardId(Integer wardId) {
        this.wardId = wardId;
    }

    
    @Column(name="first_name")
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="last_name")
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="relation")
    public String getRelation() {
        return this.relation;
    }
    
    public void setRelation(String relation) {
        this.relation = relation;
    }

    
    @Column(name="email")
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="office_phone1")
    public String getOfficePhone1() {
        return this.officePhone1;
    }
    
    public void setOfficePhone1(String officePhone1) {
        this.officePhone1 = officePhone1;
    }

    
    @Column(name="office_phone2")
    public String getOfficePhone2() {
        return this.officePhone2;
    }
    
    public void setOfficePhone2(String officePhone2) {
        this.officePhone2 = officePhone2;
    }

    
    @Column(name="mobile_phone")
    public String getMobilePhone() {
        return this.mobilePhone;
    }
    
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone;
    }

    
    @Column(name="office_address_line1")
    public String getOfficeAddressLine1() {
        return this.officeAddressLine1;
    }
    
    public void setOfficeAddressLine1(String officeAddressLine1) {
        this.officeAddressLine1 = officeAddressLine1;
    }

    
    @Column(name="office_address_line2")
    public String getOfficeAddressLine2() {
        return this.officeAddressLine2;
    }
    
    public void setOfficeAddressLine2(String officeAddressLine2) {
        this.officeAddressLine2 = officeAddressLine2;
    }

    
    @Column(name="city")
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="state")
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }

    
    @Column(name="country_id")
    public Integer getCountryId() {
        return this.countryId;
    }
    
    public void setCountryId(Integer countryId) {
        this.countryId = countryId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dob", length=10)
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }

    
    @Column(name="occupation")
    public String getOccupation() {
        return this.occupation;
    }
    
    public void setOccupation(String occupation) {
        this.occupation = occupation;
    }

    
    @Column(name="income")
    public String getIncome() {
        return this.income;
    }
    
    public void setIncome(String income) {
        this.income = income;
    }

    
    @Column(name="education")
    public String getEducation() {
        return this.education;
    }
    
    public void setEducation(String education) {
        this.education = education;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", length=19)
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at", length=19)
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }




}


