package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ArchivedEmployeeAdditionalDetails generated by hbm2java
 */
@Entity
@Table(name="archived_employee_additional_details"
    ,catalog="villaeducativa"
)
public class ArchivedEmployeeAdditionalDetails  implements java.io.Serializable {


     private Integer id;
     private Integer employeeId;
     private Integer additionalFieldId;
     private String additionalInfo;

    public ArchivedEmployeeAdditionalDetails() {
    }

    public ArchivedEmployeeAdditionalDetails(Integer employeeId, Integer additionalFieldId, String additionalInfo) {
       this.employeeId = employeeId;
       this.additionalFieldId = additionalFieldId;
       this.additionalInfo = additionalInfo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="employee_id")
    public Integer getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    
    @Column(name="additional_field_id")
    public Integer getAdditionalFieldId() {
        return this.additionalFieldId;
    }
    
    public void setAdditionalFieldId(Integer additionalFieldId) {
        this.additionalFieldId = additionalFieldId;
    }

    
    @Column(name="additional_info")
    public String getAdditionalInfo() {
        return this.additionalInfo;
    }
    
    public void setAdditionalInfo(String additionalInfo) {
        this.additionalInfo = additionalInfo;
    }




}


