package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Attendances generated by hbm2java
 */
@Entity
@Table(name="attendances"
    ,catalog="villaeducativa"
)
public class Attendances  implements java.io.Serializable {


     private Integer id;
     private Integer studentId;
     private Integer periodTableEntryId;
     private Boolean forenoon;
     private Boolean afternoon;
     private String reason;

    public Attendances() {
    }

    public Attendances(Integer studentId, Integer periodTableEntryId, Boolean forenoon, Boolean afternoon, String reason) {
       this.studentId = studentId;
       this.periodTableEntryId = periodTableEntryId;
       this.forenoon = forenoon;
       this.afternoon = afternoon;
       this.reason = reason;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="student_id")
    public Integer getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    
    @Column(name="period_table_entry_id")
    public Integer getPeriodTableEntryId() {
        return this.periodTableEntryId;
    }
    
    public void setPeriodTableEntryId(Integer periodTableEntryId) {
        this.periodTableEntryId = periodTableEntryId;
    }

    
    @Column(name="forenoon")
    public Boolean getForenoon() {
        return this.forenoon;
    }
    
    public void setForenoon(Boolean forenoon) {
        this.forenoon = forenoon;
    }

    
    @Column(name="afternoon")
    public Boolean getAfternoon() {
        return this.afternoon;
    }
    
    public void setAfternoon(Boolean afternoon) {
        this.afternoon = afternoon;
    }

    
    @Column(name="reason")
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }




}


