package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Authassignment generated by hbm2java
 */
@Entity
@Table(name="authassignment"
    ,catalog="villaeducativa"
)
public class Authassignment  implements java.io.Serializable {


     private AuthassignmentId id;
     private Authitem authitem;
     private String bizrule;
     private String data;

    public Authassignment() {
    }

	
    public Authassignment(AuthassignmentId id, Authitem authitem) {
        this.id = id;
        this.authitem = authitem;
    }
    public Authassignment(AuthassignmentId id, Authitem authitem, String bizrule, String data) {
       this.id = id;
       this.authitem = authitem;
       this.bizrule = bizrule;
       this.data = data;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="itemname", column=@Column(name="itemname", nullable=false, length=64) ), 
        @AttributeOverride(name="userid", column=@Column(name="userid", nullable=false, length=64) ) } )
    public AuthassignmentId getId() {
        return this.id;
    }
    
    public void setId(AuthassignmentId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="itemname", nullable=false, insertable=false, updatable=false)
    public Authitem getAuthitem() {
        return this.authitem;
    }
    
    public void setAuthitem(Authitem authitem) {
        this.authitem = authitem;
    }

    
    @Column(name="bizrule", length=65535)
    public String getBizrule() {
        return this.bizrule;
    }
    
    public void setBizrule(String bizrule) {
        this.bizrule = bizrule;
    }

    
    @Column(name="data", length=65535)
    public String getData() {
        return this.data;
    }
    
    public void setData(String data) {
        this.data = data;
    }




}


