package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Book generated by hbm2java
 */
@Entity
@Table(name="book"
    ,catalog="villaeducativa"
)
public class Book  implements java.io.Serializable {


     private Integer id;
     private String isbn;
     private String title;
     private String subject;
     private String category;
     private String author;
     private String edition;
     private String publisher;
     private Integer copy;
     private String copyTaken;
     private String bookPosition;
     private String shelfNo;
     private Date date;
     private String status;
     private int isDeleted;

    public Book() {
    }

	
    public Book(int isDeleted) {
        this.isDeleted = isDeleted;
    }
    public Book(String isbn, String title, String subject, String category, String author, String edition, String publisher, Integer copy, String copyTaken, String bookPosition, String shelfNo, Date date, String status, int isDeleted) {
       this.isbn = isbn;
       this.title = title;
       this.subject = subject;
       this.category = category;
       this.author = author;
       this.edition = edition;
       this.publisher = publisher;
       this.copy = copy;
       this.copyTaken = copyTaken;
       this.bookPosition = bookPosition;
       this.shelfNo = shelfNo;
       this.date = date;
       this.status = status;
       this.isDeleted = isDeleted;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="isbn", length=120)
    public String getIsbn() {
        return this.isbn;
    }
    
    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }

    
    @Column(name="title")
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="subject")
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }

    
    @Column(name="category")
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }

    
    @Column(name="author")
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }

    
    @Column(name="edition")
    public String getEdition() {
        return this.edition;
    }
    
    public void setEdition(String edition) {
        this.edition = edition;
    }

    
    @Column(name="publisher")
    public String getPublisher() {
        return this.publisher;
    }
    
    public void setPublisher(String publisher) {
        this.publisher = publisher;
    }

    
    @Column(name="copy")
    public Integer getCopy() {
        return this.copy;
    }
    
    public void setCopy(Integer copy) {
        this.copy = copy;
    }

    
    @Column(name="copy_taken", length=120)
    public String getCopyTaken() {
        return this.copyTaken;
    }
    
    public void setCopyTaken(String copyTaken) {
        this.copyTaken = copyTaken;
    }

    
    @Column(name="book_position", length=120)
    public String getBookPosition() {
        return this.bookPosition;
    }
    
    public void setBookPosition(String bookPosition) {
        this.bookPosition = bookPosition;
    }

    
    @Column(name="shelf_no", length=120)
    public String getShelfNo() {
        return this.shelfNo;
    }
    
    public void setShelfNo(String shelfNo) {
        this.shelfNo = shelfNo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date", length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="status", length=120)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="is_deleted", nullable=false)
    public int getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(int isDeleted) {
        this.isDeleted = isDeleted;
    }




}


