package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BusLog generated by hbm2java
 */
@Entity
@Table(name="bus_log"
    ,catalog="villaeducativa"
)
public class BusLog  implements java.io.Serializable {


     private Integer id;
     private String vehicleId;
     private String startTimeReading;
     private String endTimeReading;
     private String fuelConsumption;

    public BusLog() {
    }

    public BusLog(String vehicleId, String startTimeReading, String endTimeReading, String fuelConsumption) {
       this.vehicleId = vehicleId;
       this.startTimeReading = startTimeReading;
       this.endTimeReading = endTimeReading;
       this.fuelConsumption = fuelConsumption;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="vehicle_id", length=120)
    public String getVehicleId() {
        return this.vehicleId;
    }
    
    public void setVehicleId(String vehicleId) {
        this.vehicleId = vehicleId;
    }

    
    @Column(name="start_time_reading", length=120)
    public String getStartTimeReading() {
        return this.startTimeReading;
    }
    
    public void setStartTimeReading(String startTimeReading) {
        this.startTimeReading = startTimeReading;
    }

    
    @Column(name="end_time_reading", length=120)
    public String getEndTimeReading() {
        return this.endTimeReading;
    }
    
    public void setEndTimeReading(String endTimeReading) {
        this.endTimeReading = endTimeReading;
    }

    
    @Column(name="fuel_consumption", length=120)
    public String getFuelConsumption() {
        return this.fuelConsumption;
    }
    
    public void setFuelConsumption(String fuelConsumption) {
        this.fuelConsumption = fuelConsumption;
    }




}


