package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BuyProduct generated by hbm2java
 */
@Entity
@Table(name="buy_product"
    ,catalog="villaeducativa"
)
public class BuyProduct  implements java.io.Serializable {


     private Integer id;
     private int studentId;
     private String prName;
     private String prBrand;
     private Integer prQuantity;
     private int productId;
     private Date issuedDate;

    public BuyProduct() {
    }

	
    public BuyProduct(int studentId, String prName, String prBrand, int productId, Date issuedDate) {
        this.studentId = studentId;
        this.prName = prName;
        this.prBrand = prBrand;
        this.productId = productId;
        this.issuedDate = issuedDate;
    }
    public BuyProduct(int studentId, String prName, String prBrand, Integer prQuantity, int productId, Date issuedDate) {
       this.studentId = studentId;
       this.prName = prName;
       this.prBrand = prBrand;
       this.prQuantity = prQuantity;
       this.productId = productId;
       this.issuedDate = issuedDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="student_id", nullable=false)
    public int getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(int studentId) {
        this.studentId = studentId;
    }

    
    @Column(name="pr_name", nullable=false, length=200)
    public String getPrName() {
        return this.prName;
    }
    
    public void setPrName(String prName) {
        this.prName = prName;
    }

    
    @Column(name="pr_brand", nullable=false, length=200)
    public String getPrBrand() {
        return this.prBrand;
    }
    
    public void setPrBrand(String prBrand) {
        this.prBrand = prBrand;
    }

    
    @Column(name="pr_quantity")
    public Integer getPrQuantity() {
        return this.prQuantity;
    }
    
    public void setPrQuantity(Integer prQuantity) {
        this.prQuantity = prQuantity;
    }

    
    @Column(name="product_id", nullable=false)
    public int getProductId() {
        return this.productId;
    }
    
    public void setProductId(int productId) {
        this.productId = productId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="issued_date", nullable=false, length=19)
    public Date getIssuedDate() {
        return this.issuedDate;
    }
    
    public void setIssuedDate(Date issuedDate) {
        this.issuedDate = issuedDate;
    }




}


