package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CmsAttachment generated by hbm2java
 */
@Entity
@Table(name="cms_attachment"
    ,catalog="villaeducativa"
)
public class CmsAttachment  implements java.io.Serializable {


     private Integer id;
     private Date created;
     private int contentId;
     private String filename;
     private String extension;
     private String mimeType;
     private int byteSize;

    public CmsAttachment() {
    }

    public CmsAttachment(Date created, int contentId, String filename, String extension, String mimeType, int byteSize) {
       this.created = created;
       this.contentId = contentId;
       this.filename = filename;
       this.extension = extension;
       this.mimeType = mimeType;
       this.byteSize = byteSize;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created", nullable=false, length=19)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    
    @Column(name="contentId", nullable=false)
    public int getContentId() {
        return this.contentId;
    }
    
    public void setContentId(int contentId) {
        this.contentId = contentId;
    }

    
    @Column(name="filename", nullable=false)
    public String getFilename() {
        return this.filename;
    }
    
    public void setFilename(String filename) {
        this.filename = filename;
    }

    
    @Column(name="extension", nullable=false, length=50)
    public String getExtension() {
        return this.extension;
    }
    
    public void setExtension(String extension) {
        this.extension = extension;
    }

    
    @Column(name="mimeType", nullable=false)
    public String getMimeType() {
        return this.mimeType;
    }
    
    public void setMimeType(String mimeType) {
        this.mimeType = mimeType;
    }

    
    @Column(name="byteSize", nullable=false)
    public int getByteSize() {
        return this.byteSize;
    }
    
    public void setByteSize(int byteSize) {
        this.byteSize = byteSize;
    }




}


