package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CmsContent generated by hbm2java
 */
@Entity
@Table(name="cms_content"
    ,catalog="villaeducativa"
    , uniqueConstraints = @UniqueConstraint(columnNames={"nodeId", "locale"}) 
)
public class CmsContent  implements java.io.Serializable {


     private Integer id;
     private int nodeId;
     private String locale;
     private String heading;
     private String body;
     private String css;
     private String url;
     private String pageTitle;
     private String breadcrumb;
     private String metaTitle;
     private String metaDescription;
     private String metaKeywords;

    public CmsContent() {
    }

	
    public CmsContent(int nodeId, String locale) {
        this.nodeId = nodeId;
        this.locale = locale;
    }
    public CmsContent(int nodeId, String locale, String heading, String body, String css, String url, String pageTitle, String breadcrumb, String metaTitle, String metaDescription, String metaKeywords) {
       this.nodeId = nodeId;
       this.locale = locale;
       this.heading = heading;
       this.body = body;
       this.css = css;
       this.url = url;
       this.pageTitle = pageTitle;
       this.breadcrumb = breadcrumb;
       this.metaTitle = metaTitle;
       this.metaDescription = metaDescription;
       this.metaKeywords = metaKeywords;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="nodeId", nullable=false)
    public int getNodeId() {
        return this.nodeId;
    }
    
    public void setNodeId(int nodeId) {
        this.nodeId = nodeId;
    }

    
    @Column(name="locale", nullable=false, length=50)
    public String getLocale() {
        return this.locale;
    }
    
    public void setLocale(String locale) {
        this.locale = locale;
    }

    
    @Column(name="heading")
    public String getHeading() {
        return this.heading;
    }
    
    public void setHeading(String heading) {
        this.heading = heading;
    }

    
    @Column(name="body")
    public String getBody() {
        return this.body;
    }
    
    public void setBody(String body) {
        this.body = body;
    }

    
    @Column(name="css")
    public String getCss() {
        return this.css;
    }
    
    public void setCss(String css) {
        this.css = css;
    }

    
    @Column(name="url")
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }

    
    @Column(name="pageTitle")
    public String getPageTitle() {
        return this.pageTitle;
    }
    
    public void setPageTitle(String pageTitle) {
        this.pageTitle = pageTitle;
    }

    
    @Column(name="breadcrumb")
    public String getBreadcrumb() {
        return this.breadcrumb;
    }
    
    public void setBreadcrumb(String breadcrumb) {
        this.breadcrumb = breadcrumb;
    }

    
    @Column(name="metaTitle")
    public String getMetaTitle() {
        return this.metaTitle;
    }
    
    public void setMetaTitle(String metaTitle) {
        this.metaTitle = metaTitle;
    }

    
    @Column(name="metaDescription")
    public String getMetaDescription() {
        return this.metaDescription;
    }
    
    public void setMetaDescription(String metaDescription) {
        this.metaDescription = metaDescription;
    }

    
    @Column(name="metaKeywords")
    public String getMetaKeywords() {
        return this.metaKeywords;
    }
    
    public void setMetaKeywords(String metaKeywords) {
        this.metaKeywords = metaKeywords;
    }




}


