package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CmsNode generated by hbm2java
 */
@Entity
@Table(name="cms_node"
    ,catalog="villaeducativa"
)
public class CmsNode  implements java.io.Serializable {


     private Integer id;
     private Date created;
     private Date updated;
     private int parentId;
     private String name;
     private byte deleted;

    public CmsNode() {
    }

	
    public CmsNode(Date created, int parentId, String name, byte deleted) {
        this.created = created;
        this.parentId = parentId;
        this.name = name;
        this.deleted = deleted;
    }
    public CmsNode(Date created, Date updated, int parentId, String name, byte deleted) {
       this.created = created;
       this.updated = updated;
       this.parentId = parentId;
       this.name = name;
       this.deleted = deleted;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created", nullable=false, length=19)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated", length=19)
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    
    @Column(name="parentId", nullable=false)
    public int getParentId() {
        return this.parentId;
    }
    
    public void setParentId(int parentId) {
        this.parentId = parentId;
    }

    
    @Column(name="name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="deleted", nullable=false)
    public byte getDeleted() {
        return this.deleted;
    }
    
    public void setDeleted(byte deleted) {
        this.deleted = deleted;
    }




}


