package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DriverDetails generated by hbm2java
 */
@Entity
@Table(name="driver_details"
    ,catalog="villaeducativa"
)
public class DriverDetails  implements java.io.Serializable {


     private Integer id;
     private String vehicleId;
     private String firstName;
     private String lastName;
     private String address;
     private String dob;
     private String age;
     private String licenseNo;
     private Date expiryDate;
     private String status;

    public DriverDetails() {
    }

    public DriverDetails(String vehicleId, String firstName, String lastName, String address, String dob, String age, String licenseNo, Date expiryDate, String status) {
       this.vehicleId = vehicleId;
       this.firstName = firstName;
       this.lastName = lastName;
       this.address = address;
       this.dob = dob;
       this.age = age;
       this.licenseNo = licenseNo;
       this.expiryDate = expiryDate;
       this.status = status;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="vehicle_id", length=120)
    public String getVehicleId() {
        return this.vehicleId;
    }
    
    public void setVehicleId(String vehicleId) {
        this.vehicleId = vehicleId;
    }

    
    @Column(name="first_name", length=120)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="last_name", length=120)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="address", length=120)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="dob", length=120)
    public String getDob() {
        return this.dob;
    }
    
    public void setDob(String dob) {
        this.dob = dob;
    }

    
    @Column(name="age", length=120)
    public String getAge() {
        return this.age;
    }
    
    public void setAge(String age) {
        this.age = age;
    }

    
    @Column(name="license_no", length=120)
    public String getLicenseNo() {
        return this.licenseNo;
    }
    
    public void setLicenseNo(String licenseNo) {
        this.licenseNo = licenseNo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="expiry_date", length=10)
    public Date getExpiryDate() {
        return this.expiryDate;
    }
    
    public void setExpiryDate(Date expiryDate) {
        this.expiryDate = expiryDate;
    }

    
    @Column(name="status", length=120)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


