package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EmployeeLeaveTypes generated by hbm2java
 */
@Entity
@Table(name="employee_leave_types"
    ,catalog="villaeducativa"
)
public class EmployeeLeaveTypes  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String code;
     private Boolean status;
     private String maxLeaveCount;
     private boolean carryForward;

    public EmployeeLeaveTypes() {
    }

	
    public EmployeeLeaveTypes(boolean carryForward) {
        this.carryForward = carryForward;
    }
    public EmployeeLeaveTypes(String name, String code, Boolean status, String maxLeaveCount, boolean carryForward) {
       this.name = name;
       this.code = code;
       this.status = status;
       this.maxLeaveCount = maxLeaveCount;
       this.carryForward = carryForward;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="code")
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="status")
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }

    
    @Column(name="max_leave_count")
    public String getMaxLeaveCount() {
        return this.maxLeaveCount;
    }
    
    public void setMaxLeaveCount(String maxLeaveCount) {
        this.maxLeaveCount = maxLeaveCount;
    }

    
    @Column(name="carry_forward", nullable=false)
    public boolean isCarryForward() {
        return this.carryForward;
    }
    
    public void setCarryForward(boolean carryForward) {
        this.carryForward = carryForward;
    }




}


