package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EmployeeGrades generated by hbm2java
 */
@Entity
@Table(name="employee_grades"
    ,catalog="villaeducativa"
)
public class EmployeeGrades  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Integer priority;
     private Boolean status;
     private Integer maxHoursDay;
     private Integer maxHoursWeek;

    public EmployeeGrades() {
    }

    public EmployeeGrades(String name, Integer priority, Boolean status, Integer maxHoursDay, Integer maxHoursWeek) {
       this.name = name;
       this.priority = priority;
       this.status = status;
       this.maxHoursDay = maxHoursDay;
       this.maxHoursWeek = maxHoursWeek;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="priority")
    public Integer getPriority() {
        return this.priority;
    }
    
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    
    @Column(name="status")
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }

    
    @Column(name="max_hours_day")
    public Integer getMaxHoursDay() {
        return this.maxHoursDay;
    }
    
    public void setMaxHoursDay(Integer maxHoursDay) {
        this.maxHoursDay = maxHoursDay;
    }

    
    @Column(name="max_hours_week")
    public Integer getMaxHoursWeek() {
        return this.maxHoursWeek;
    }
    
    public void setMaxHoursWeek(Integer maxHoursWeek) {
        this.maxHoursWeek = maxHoursWeek;
    }




}


