package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmployeeDepartmentEvents generated by hbm2java
 */
@Entity
@Table(name="employee_department_events"
    ,catalog="villaeducativa"
)
public class EmployeeDepartmentEvents  implements java.io.Serializable {


     private Integer id;
     private Integer eventId;
     private Integer employeeDepartmentId;
     private Date createdAt;
     private Date updatedAt;

    public EmployeeDepartmentEvents() {
    }

    public EmployeeDepartmentEvents(Integer eventId, Integer employeeDepartmentId, Date createdAt, Date updatedAt) {
       this.eventId = eventId;
       this.employeeDepartmentId = employeeDepartmentId;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="event_id")
    public Integer getEventId() {
        return this.eventId;
    }
    
    public void setEventId(Integer eventId) {
        this.eventId = eventId;
    }

    
    @Column(name="employee_department_id")
    public Integer getEmployeeDepartmentId() {
        return this.employeeDepartmentId;
    }
    
    public void setEmployeeDepartmentId(Integer employeeDepartmentId) {
        this.employeeDepartmentId = employeeDepartmentId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", length=19)
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at", length=19)
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }




}


