package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EmployeeSalaryStructures generated by hbm2java
 */
@Entity
@Table(name="employee_salary_structures"
    ,catalog="villaeducativa"
)
public class EmployeeSalaryStructures  implements java.io.Serializable {


     private Integer id;
     private Integer employeeId;
     private Integer payrollCategoryId;
     private String amount;

    public EmployeeSalaryStructures() {
    }

    public EmployeeSalaryStructures(Integer employeeId, Integer payrollCategoryId, String amount) {
       this.employeeId = employeeId;
       this.payrollCategoryId = payrollCategoryId;
       this.amount = amount;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="employee_id")
    public Integer getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    
    @Column(name="payroll_category_id")
    public Integer getPayrollCategoryId() {
        return this.payrollCategoryId;
    }
    
    public void setPayrollCategoryId(Integer payrollCategoryId) {
        this.payrollCategoryId = payrollCategoryId;
    }

    
    @Column(name="amount")
    public String getAmount() {
        return this.amount;
    }
    
    public void setAmount(String amount) {
        this.amount = amount;
    }




}


