package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EmployeeBankDetails generated by hbm2java
 */
@Entity
@Table(name="employee_bank_details"
    ,catalog="villaeducativa"
)
public class EmployeeBankDetails  implements java.io.Serializable {


     private Integer id;
     private Integer employeeId;
     private Integer bankFieldId;
     private String bankInfo;

    public EmployeeBankDetails() {
    }

    public EmployeeBankDetails(Integer employeeId, Integer bankFieldId, String bankInfo) {
       this.employeeId = employeeId;
       this.bankFieldId = bankFieldId;
       this.bankInfo = bankInfo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="employee_id")
    public Integer getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    
    @Column(name="bank_field_id")
    public Integer getBankFieldId() {
        return this.bankFieldId;
    }
    
    public void setBankFieldId(Integer bankFieldId) {
        this.bankFieldId = bankFieldId;
    }

    
    @Column(name="bank_info")
    public String getBankInfo() {
        return this.bankInfo;
    }
    
    public void setBankInfo(String bankInfo) {
        this.bankInfo = bankInfo;
    }




}


