package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmployeeLeaves generated by hbm2java
 */
@Entity
@Table(name="employee_leaves"
    ,catalog="villaeducativa"
)
public class EmployeeLeaves  implements java.io.Serializable {


     private Integer id;
     private Integer employeeId;
     private Integer employeeLeaveTypeId;
     private BigDecimal leaveCount;
     private BigDecimal leaveTaken;
     private Date resetDate;
     private Date createdAt;
     private Date updatedAt;

    public EmployeeLeaves() {
    }

    public EmployeeLeaves(Integer employeeId, Integer employeeLeaveTypeId, BigDecimal leaveCount, BigDecimal leaveTaken, Date resetDate, Date createdAt, Date updatedAt) {
       this.employeeId = employeeId;
       this.employeeLeaveTypeId = employeeLeaveTypeId;
       this.leaveCount = leaveCount;
       this.leaveTaken = leaveTaken;
       this.resetDate = resetDate;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="employee_id")
    public Integer getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    
    @Column(name="employee_leave_type_id")
    public Integer getEmployeeLeaveTypeId() {
        return this.employeeLeaveTypeId;
    }
    
    public void setEmployeeLeaveTypeId(Integer employeeLeaveTypeId) {
        this.employeeLeaveTypeId = employeeLeaveTypeId;
    }

    
    @Column(name="leave_count", precision=5, scale=1)
    public BigDecimal getLeaveCount() {
        return this.leaveCount;
    }
    
    public void setLeaveCount(BigDecimal leaveCount) {
        this.leaveCount = leaveCount;
    }

    
    @Column(name="leave_taken", precision=5, scale=1)
    public BigDecimal getLeaveTaken() {
        return this.leaveTaken;
    }
    
    public void setLeaveTaken(BigDecimal leaveTaken) {
        this.leaveTaken = leaveTaken;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="reset_date", length=10)
    public Date getResetDate() {
        return this.resetDate;
    }
    
    public void setResetDate(Date resetDate) {
        this.resetDate = resetDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", length=19)
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at", length=19)
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }




}


