package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EventsOld generated by hbm2java
 */
@Entity
@Table(name="events_old"
    ,catalog="villaeducativa"
)
public class EventsOld  implements java.io.Serializable {


     private Integer id;
     private String title;
     private String description;
     private Date startDate;
     private Date endDate;
     private Boolean isCommon;
     private Boolean isHoliday;
     private Boolean isExam;
     private Boolean isDue;
     private Date createdAt;
     private Date updatedAt;
     private Integer originId;
     private String originType;

    public EventsOld() {
    }

    public EventsOld(String title, String description, Date startDate, Date endDate, Boolean isCommon, Boolean isHoliday, Boolean isExam, Boolean isDue, Date createdAt, Date updatedAt, Integer originId, String originType) {
       this.title = title;
       this.description = description;
       this.startDate = startDate;
       this.endDate = endDate;
       this.isCommon = isCommon;
       this.isHoliday = isHoliday;
       this.isExam = isExam;
       this.isDue = isDue;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.originId = originId;
       this.originType = originType;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="title")
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="start_date", length=19)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="end_date", length=19)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    
    @Column(name="is_common")
    public Boolean getIsCommon() {
        return this.isCommon;
    }
    
    public void setIsCommon(Boolean isCommon) {
        this.isCommon = isCommon;
    }

    
    @Column(name="is_holiday")
    public Boolean getIsHoliday() {
        return this.isHoliday;
    }
    
    public void setIsHoliday(Boolean isHoliday) {
        this.isHoliday = isHoliday;
    }

    
    @Column(name="is_exam")
    public Boolean getIsExam() {
        return this.isExam;
    }
    
    public void setIsExam(Boolean isExam) {
        this.isExam = isExam;
    }

    
    @Column(name="is_due")
    public Boolean getIsDue() {
        return this.isDue;
    }
    
    public void setIsDue(Boolean isDue) {
        this.isDue = isDue;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", length=19)
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at", length=19)
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    
    @Column(name="origin_id")
    public Integer getOriginId() {
        return this.originId;
    }
    
    public void setOriginId(Integer originId) {
        this.originId = originId;
    }

    
    @Column(name="origin_type")
    public String getOriginType() {
        return this.originType;
    }
    
    public void setOriginType(String originType) {
        this.originType = originType;
    }




}


