package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EventsType generated by hbm2java
 */
@Entity
@Table(name="events_type"
    ,catalog="villaeducativa"
)
public class EventsType  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String colourCode;

    public EventsType() {
    }

    public EventsType(String name, String colourCode) {
       this.name = name;
       this.colourCode = colourCode;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", length=120)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="colour_code", length=120)
    public String getColourCode() {
        return this.colourCode;
    }
    
    public void setColourCode(String colourCode) {
        this.colourCode = colourCode;
    }




}


