package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EventsUserPreference generated by hbm2java
 */
@Entity
@Table(name="events_user_preference"
    ,catalog="villaeducativa"
)
public class EventsUserPreference  implements java.io.Serializable {


     private int userId;
     private String mobile;
     private boolean mobileAlert;
     private String email;
     private boolean emailAlert;

    public EventsUserPreference() {
    }

	
    public EventsUserPreference(int userId, boolean mobileAlert, boolean emailAlert) {
        this.userId = userId;
        this.mobileAlert = mobileAlert;
        this.emailAlert = emailAlert;
    }
    public EventsUserPreference(int userId, String mobile, boolean mobileAlert, String email, boolean emailAlert) {
       this.userId = userId;
       this.mobile = mobile;
       this.mobileAlert = mobileAlert;
       this.email = email;
       this.emailAlert = emailAlert;
    }
   
     @Id 

    
    @Column(name="user_id", unique=true, nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }

    
    @Column(name="mobile", length=20)
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    
    @Column(name="mobile_alert", nullable=false)
    public boolean isMobileAlert() {
        return this.mobileAlert;
    }
    
    public void setMobileAlert(boolean mobileAlert) {
        this.mobileAlert = mobileAlert;
    }

    
    @Column(name="email", length=40)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="email_alert", nullable=false)
    public boolean isEmailAlert() {
        return this.emailAlert;
    }
    
    public void setEmailAlert(boolean emailAlert) {
        this.emailAlert = emailAlert;
    }




}


