package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EventsHelper generated by hbm2java
 */
@Entity
@Table(name="events_helper"
    ,catalog="villaeducativa"
)
public class EventsHelper  implements java.io.Serializable {


     private Integer id;
     private int type;
     private int userId;
     private String title;

    public EventsHelper() {
    }

	
    public EventsHelper(int type, int userId) {
        this.type = type;
        this.userId = userId;
    }
    public EventsHelper(int type, int userId, String title) {
       this.type = type;
       this.userId = userId;
       this.title = title;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="type", nullable=false)
    public int getType() {
        return this.type;
    }
    
    public void setType(int type) {
        this.type = type;
    }

    
    @Column(name="user_id", nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }

    
    @Column(name="title", length=1000)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }




}


