package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FeeCollectionDiscounts generated by hbm2java
 */
@Entity
@Table(name="fee_collection_discounts"
    ,catalog="villaeducativa"
)
public class FeeCollectionDiscounts  implements java.io.Serializable {


     private Integer id;
     private String type;
     private String name;
     private Integer receiverId;
     private Integer financeFeeCollectionId;
     private BigDecimal discount;
     private Boolean isAmount;
     private Date createdAt;
     private Date updatedAt;

    public FeeCollectionDiscounts() {
    }

    public FeeCollectionDiscounts(String type, String name, Integer receiverId, Integer financeFeeCollectionId, BigDecimal discount, Boolean isAmount, Date createdAt, Date updatedAt) {
       this.type = type;
       this.name = name;
       this.receiverId = receiverId;
       this.financeFeeCollectionId = financeFeeCollectionId;
       this.discount = discount;
       this.isAmount = isAmount;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="type")
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="receiver_id")
    public Integer getReceiverId() {
        return this.receiverId;
    }
    
    public void setReceiverId(Integer receiverId) {
        this.receiverId = receiverId;
    }

    
    @Column(name="finance_fee_collection_id")
    public Integer getFinanceFeeCollectionId() {
        return this.financeFeeCollectionId;
    }
    
    public void setFinanceFeeCollectionId(Integer financeFeeCollectionId) {
        this.financeFeeCollectionId = financeFeeCollectionId;
    }

    
    @Column(name="discount", precision=15)
    public BigDecimal getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

    
    @Column(name="is_amount")
    public Boolean getIsAmount() {
        return this.isAmount;
    }
    
    public void setIsAmount(Boolean isAmount) {
        this.isAmount = isAmount;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", length=19)
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at", length=19)
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }




}


