package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FeeDiscounts generated by hbm2java
 */
@Entity
@Table(name="fee_discounts"
    ,catalog="villaeducativa"
)
public class FeeDiscounts  implements java.io.Serializable {


     private Integer id;
     private String type;
     private String name;
     private Integer receiverId;
     private Integer financeFeeCategoryId;
     private BigDecimal discount;
     private Boolean isAmount;

    public FeeDiscounts() {
    }

    public FeeDiscounts(String type, String name, Integer receiverId, Integer financeFeeCategoryId, BigDecimal discount, Boolean isAmount) {
       this.type = type;
       this.name = name;
       this.receiverId = receiverId;
       this.financeFeeCategoryId = financeFeeCategoryId;
       this.discount = discount;
       this.isAmount = isAmount;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="type")
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="receiver_id")
    public Integer getReceiverId() {
        return this.receiverId;
    }
    
    public void setReceiverId(Integer receiverId) {
        this.receiverId = receiverId;
    }

    
    @Column(name="finance_fee_category_id")
    public Integer getFinanceFeeCategoryId() {
        return this.financeFeeCategoryId;
    }
    
    public void setFinanceFeeCategoryId(Integer financeFeeCategoryId) {
        this.financeFeeCategoryId = financeFeeCategoryId;
    }

    
    @Column(name="discount", precision=15)
    public BigDecimal getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

    
    @Column(name="is_amount")
    public Boolean getIsAmount() {
        return this.isAmount;
    }
    
    public void setIsAmount(Boolean isAmount) {
        this.isAmount = isAmount;
    }




}


