package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FeeReceiptDetails generated by hbm2java
 */
@Entity
@Table(name="fee_receipt_details"
    ,catalog="villaeducativa"
)
public class FeeReceiptDetails  implements java.io.Serializable {


     private Integer id;
     private int student;
     private int batch;
     private int collection;

    public FeeReceiptDetails() {
    }

    public FeeReceiptDetails(int student, int batch, int collection) {
       this.student = student;
       this.batch = batch;
       this.collection = collection;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="student", nullable=false)
    public int getStudent() {
        return this.student;
    }
    
    public void setStudent(int student) {
        this.student = student;
    }

    
    @Column(name="batch", nullable=false)
    public int getBatch() {
        return this.batch;
    }
    
    public void setBatch(int batch) {
        this.batch = batch;
    }

    
    @Column(name="collection", nullable=false)
    public int getCollection() {
        return this.collection;
    }
    
    public void setCollection(int collection) {
        this.collection = collection;
    }




}


