package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FinanceFees generated by hbm2java
 */
@Entity
@Table(name="finance_fees"
    ,catalog="villaeducativa"
)
public class FinanceFees  implements java.io.Serializable {


     private Integer id;
     private Integer feeCollectionId;
     private String transactionId;
     private Integer studentId;
     private Boolean isPaid;

    public FinanceFees() {
    }

    public FinanceFees(Integer feeCollectionId, String transactionId, Integer studentId, Boolean isPaid) {
       this.feeCollectionId = feeCollectionId;
       this.transactionId = transactionId;
       this.studentId = studentId;
       this.isPaid = isPaid;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="fee_collection_id")
    public Integer getFeeCollectionId() {
        return this.feeCollectionId;
    }
    
    public void setFeeCollectionId(Integer feeCollectionId) {
        this.feeCollectionId = feeCollectionId;
    }

    
    @Column(name="transaction_id")
    public String getTransactionId() {
        return this.transactionId;
    }
    
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
    }

    
    @Column(name="student_id")
    public Integer getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    
    @Column(name="is_paid")
    public Boolean getIsPaid() {
        return this.isPaid;
    }
    
    public void setIsPaid(Boolean isPaid) {
        this.isPaid = isPaid;
    }




}


