package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FinanceTransactions generated by hbm2java
 */
@Entity
@Table(name="finance_transactions"
    ,catalog="villaeducativa"
)
public class FinanceTransactions  implements java.io.Serializable {


     private Integer id;
     private String title;
     private String description;
     private BigDecimal amount;
     private Boolean fineIncluded;
     private Integer categoryId;
     private Integer studentId;
     private Integer financeFeesId;
     private Date createdAt;
     private Date updatedAt;
     private Date transactionDate;
     private BigDecimal fineAmount;
     private Integer masterTransactionId;
     private Integer financeId;
     private String financeType;
     private Integer payeeId;
     private String payeeType;
     private String receiptNo;
     private String voucherNo;

    public FinanceTransactions() {
    }

    public FinanceTransactions(String title, String description, BigDecimal amount, Boolean fineIncluded, Integer categoryId, Integer studentId, Integer financeFeesId, Date createdAt, Date updatedAt, Date transactionDate, BigDecimal fineAmount, Integer masterTransactionId, Integer financeId, String financeType, Integer payeeId, String payeeType, String receiptNo, String voucherNo) {
       this.title = title;
       this.description = description;
       this.amount = amount;
       this.fineIncluded = fineIncluded;
       this.categoryId = categoryId;
       this.studentId = studentId;
       this.financeFeesId = financeFeesId;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.transactionDate = transactionDate;
       this.fineAmount = fineAmount;
       this.masterTransactionId = masterTransactionId;
       this.financeId = financeId;
       this.financeType = financeType;
       this.payeeId = payeeId;
       this.payeeType = payeeType;
       this.receiptNo = receiptNo;
       this.voucherNo = voucherNo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="title")
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="amount", precision=15)
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    
    @Column(name="fine_included")
    public Boolean getFineIncluded() {
        return this.fineIncluded;
    }
    
    public void setFineIncluded(Boolean fineIncluded) {
        this.fineIncluded = fineIncluded;
    }

    
    @Column(name="category_id")
    public Integer getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    
    @Column(name="student_id")
    public Integer getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    
    @Column(name="finance_fees_id")
    public Integer getFinanceFeesId() {
        return this.financeFeesId;
    }
    
    public void setFinanceFeesId(Integer financeFeesId) {
        this.financeFeesId = financeFeesId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", length=19)
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at", length=19)
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="transaction_date", length=10)
    public Date getTransactionDate() {
        return this.transactionDate;
    }
    
    public void setTransactionDate(Date transactionDate) {
        this.transactionDate = transactionDate;
    }

    
    @Column(name="fine_amount", precision=10)
    public BigDecimal getFineAmount() {
        return this.fineAmount;
    }
    
    public void setFineAmount(BigDecimal fineAmount) {
        this.fineAmount = fineAmount;
    }

    
    @Column(name="master_transaction_id")
    public Integer getMasterTransactionId() {
        return this.masterTransactionId;
    }
    
    public void setMasterTransactionId(Integer masterTransactionId) {
        this.masterTransactionId = masterTransactionId;
    }

    
    @Column(name="finance_id")
    public Integer getFinanceId() {
        return this.financeId;
    }
    
    public void setFinanceId(Integer financeId) {
        this.financeId = financeId;
    }

    
    @Column(name="finance_type")
    public String getFinanceType() {
        return this.financeType;
    }
    
    public void setFinanceType(String financeType) {
        this.financeType = financeType;
    }

    
    @Column(name="payee_id")
    public Integer getPayeeId() {
        return this.payeeId;
    }
    
    public void setPayeeId(Integer payeeId) {
        this.payeeId = payeeId;
    }

    
    @Column(name="payee_type")
    public String getPayeeType() {
        return this.payeeType;
    }
    
    public void setPayeeType(String payeeType) {
        this.payeeType = payeeType;
    }

    
    @Column(name="receipt_no")
    public String getReceiptNo() {
        return this.receiptNo;
    }
    
    public void setReceiptNo(String receiptNo) {
        this.receiptNo = receiptNo;
    }

    
    @Column(name="voucher_no")
    public String getVoucherNo() {
        return this.voucherNo;
    }
    
    public void setVoucherNo(String voucherNo) {
        this.voucherNo = voucherNo;
    }




}


