package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FinanceTransactionTriggers generated by hbm2java
 */
@Entity
@Table(name="finance_transaction_triggers"
    ,catalog="villaeducativa"
)
public class FinanceTransactionTriggers  implements java.io.Serializable {


     private Integer id;
     private Integer financeCategoryId;
     private BigDecimal percentage;
     private String title;
     private String description;

    public FinanceTransactionTriggers() {
    }

    public FinanceTransactionTriggers(Integer financeCategoryId, BigDecimal percentage, String title, String description) {
       this.financeCategoryId = financeCategoryId;
       this.percentage = percentage;
       this.title = title;
       this.description = description;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="finance_category_id")
    public Integer getFinanceCategoryId() {
        return this.financeCategoryId;
    }
    
    public void setFinanceCategoryId(Integer financeCategoryId) {
        this.financeCategoryId = financeCategoryId;
    }

    
    @Column(name="percentage", precision=8)
    public BigDecimal getPercentage() {
        return this.percentage;
    }
    
    public void setPercentage(BigDecimal percentage) {
        this.percentage = percentage;
    }

    
    @Column(name="title")
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


