package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FinanceFeeStructureElements generated by hbm2java
 */
@Entity
@Table(name="finance_fee_structure_elements"
    ,catalog="villaeducativa"
)
public class FinanceFeeStructureElements  implements java.io.Serializable {


     private Integer id;
     private BigDecimal amount;
     private String label;
     private Integer batchId;
     private Integer studentCategoryId;
     private Integer studentId;
     private Integer parentId;
     private Integer feeCollectionId;
     private Boolean deleted;

    public FinanceFeeStructureElements() {
    }

    public FinanceFeeStructureElements(BigDecimal amount, String label, Integer batchId, Integer studentCategoryId, Integer studentId, Integer parentId, Integer feeCollectionId, Boolean deleted) {
       this.amount = amount;
       this.label = label;
       this.batchId = batchId;
       this.studentCategoryId = studentCategoryId;
       this.studentId = studentId;
       this.parentId = parentId;
       this.feeCollectionId = feeCollectionId;
       this.deleted = deleted;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="amount", precision=15)
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    
    @Column(name="label")
    public String getLabel() {
        return this.label;
    }
    
    public void setLabel(String label) {
        this.label = label;
    }

    
    @Column(name="batch_id")
    public Integer getBatchId() {
        return this.batchId;
    }
    
    public void setBatchId(Integer batchId) {
        this.batchId = batchId;
    }

    
    @Column(name="student_category_id")
    public Integer getStudentCategoryId() {
        return this.studentCategoryId;
    }
    
    public void setStudentCategoryId(Integer studentCategoryId) {
        this.studentCategoryId = studentCategoryId;
    }

    
    @Column(name="student_id")
    public Integer getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    
    @Column(name="parent_id")
    public Integer getParentId() {
        return this.parentId;
    }
    
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    
    @Column(name="fee_collection_id")
    public Integer getFeeCollectionId() {
        return this.feeCollectionId;
    }
    
    public void setFeeCollectionId(Integer feeCollectionId) {
        this.feeCollectionId = feeCollectionId;
    }

    
    @Column(name="deleted")
    public Boolean getDeleted() {
        return this.deleted;
    }
    
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }




}


