package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FinanceFeeParticulars generated by hbm2java
 */
@Entity
@Table(name="finance_fee_particulars"
    ,catalog="villaeducativa"
)
public class FinanceFeeParticulars  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String description;
     private BigDecimal amount;
     private Integer financeFeeCategoryId;
     private Integer studentCategoryId;
     private String admissionNo;
     private Integer studentId;
     private boolean isDeleted;
     private Date createdAt;
     private Date updatedAt;

    public FinanceFeeParticulars() {
    }

	
    public FinanceFeeParticulars(boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
    public FinanceFeeParticulars(String name, String description, BigDecimal amount, Integer financeFeeCategoryId, Integer studentCategoryId, String admissionNo, Integer studentId, boolean isDeleted, Date createdAt, Date updatedAt) {
       this.name = name;
       this.description = description;
       this.amount = amount;
       this.financeFeeCategoryId = financeFeeCategoryId;
       this.studentCategoryId = studentCategoryId;
       this.admissionNo = admissionNo;
       this.studentId = studentId;
       this.isDeleted = isDeleted;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="description", length=65535)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="amount", precision=15)
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    
    @Column(name="finance_fee_category_id")
    public Integer getFinanceFeeCategoryId() {
        return this.financeFeeCategoryId;
    }
    
    public void setFinanceFeeCategoryId(Integer financeFeeCategoryId) {
        this.financeFeeCategoryId = financeFeeCategoryId;
    }

    
    @Column(name="student_category_id")
    public Integer getStudentCategoryId() {
        return this.studentCategoryId;
    }
    
    public void setStudentCategoryId(Integer studentCategoryId) {
        this.studentCategoryId = studentCategoryId;
    }

    
    @Column(name="admission_no")
    public String getAdmissionNo() {
        return this.admissionNo;
    }
    
    public void setAdmissionNo(String admissionNo) {
        this.admissionNo = admissionNo;
    }

    
    @Column(name="student_id")
    public Integer getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    
    @Column(name="is_deleted", nullable=false)
    public boolean isIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", length=19)
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at", length=19)
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }




}


