package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FinanceTransactionCategories generated by hbm2java
 */
@Entity
@Table(name="finance_transaction_categories"
    ,catalog="villaeducativa"
)
public class FinanceTransactionCategories  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String description;
     private Boolean isIncome;
     private boolean deleted;

    public FinanceTransactionCategories() {
    }

	
    public FinanceTransactionCategories(boolean deleted) {
        this.deleted = deleted;
    }
    public FinanceTransactionCategories(String name, String description, Boolean isIncome, boolean deleted) {
       this.name = name;
       this.description = description;
       this.isIncome = isIncome;
       this.deleted = deleted;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="is_income")
    public Boolean getIsIncome() {
        return this.isIncome;
    }
    
    public void setIsIncome(Boolean isIncome) {
        this.isIncome = isIncome;
    }

    
    @Column(name="deleted", nullable=false)
    public boolean isDeleted() {
        return this.deleted;
    }
    
    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }




}


