package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Folder generated by hbm2java
 */
@Entity
@Table(name="folder"
    ,catalog="villaeducativa"
)
public class Folder  implements java.io.Serializable {


     private Integer id;
     private int uid;
     private int mid;
     private int fid;

    public Folder() {
    }

    public Folder(int uid, int mid, int fid) {
       this.uid = uid;
       this.mid = mid;
       this.fid = fid;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="uid", nullable=false)
    public int getUid() {
        return this.uid;
    }
    
    public void setUid(int uid) {
        this.uid = uid;
    }

    
    @Column(name="mid", nullable=false)
    public int getMid() {
        return this.mid;
    }
    
    public void setMid(int mid) {
        this.mid = mid;
    }

    
    @Column(name="fid", nullable=false)
    public int getFid() {
        return this.fid;
    }
    
    public void setFid(int fid) {
        this.fid = fid;
    }




}


