package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FoodInfo generated by hbm2java
 */
@Entity
@Table(name="food_info"
    ,catalog="villaeducativa"
)
public class FoodInfo  implements java.io.Serializable {


     private Integer id;
     private String foodPreference;
     private String amount;
     private int isDeleted;

    public FoodInfo() {
    }

	
    public FoodInfo(int isDeleted) {
        this.isDeleted = isDeleted;
    }
    public FoodInfo(String foodPreference, String amount, int isDeleted) {
       this.foodPreference = foodPreference;
       this.amount = amount;
       this.isDeleted = isDeleted;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="food_preference", length=120)
    public String getFoodPreference() {
        return this.foodPreference;
    }
    
    public void setFoodPreference(String foodPreference) {
        this.foodPreference = foodPreference;
    }

    
    @Column(name="amount", length=120)
    public String getAmount() {
        return this.amount;
    }
    
    public void setAmount(String amount) {
        this.amount = amount;
    }

    
    @Column(name="is_deleted", nullable=false)
    public int getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(int isDeleted) {
        this.isDeleted = isDeleted;
    }




}


