package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FuelConsumption generated by hbm2java
 */
@Entity
@Table(name="fuel_consumption"
    ,catalog="villaeducativa"
)
public class FuelConsumption  implements java.io.Serializable {


     private Integer id;
     private String vehicleId;
     private String fuelConsumed;
     private String amount;
     private Date consumedDate;

    public FuelConsumption() {
    }

    public FuelConsumption(String vehicleId, String fuelConsumed, String amount, Date consumedDate) {
       this.vehicleId = vehicleId;
       this.fuelConsumed = fuelConsumed;
       this.amount = amount;
       this.consumedDate = consumedDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="vehicle_id", length=120)
    public String getVehicleId() {
        return this.vehicleId;
    }
    
    public void setVehicleId(String vehicleId) {
        this.vehicleId = vehicleId;
    }

    
    @Column(name="fuel_consumed", length=120)
    public String getFuelConsumed() {
        return this.fuelConsumed;
    }
    
    public void setFuelConsumed(String fuelConsumed) {
        this.fuelConsumed = fuelConsumed;
    }

    
    @Column(name="amount", length=120)
    public String getAmount() {
        return this.amount;
    }
    
    public void setAmount(String amount) {
        this.amount = amount;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="consumed_date", length=10)
    public Date getConsumedDate() {
        return this.consumedDate;
    }
    
    public void setConsumedDate(Date consumedDate) {
        this.consumedDate = consumedDate;
    }




}


