package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Groups generated by hbm2java
 */
@Entity
@Table(name="groups"
    ,catalog="villaeducativa"
)
public class Groups  implements java.io.Serializable {


     private Integer id;
     private String grpName;
     private String usersIds;

    public Groups() {
    }

    public Groups(String grpName, String usersIds) {
       this.grpName = grpName;
       this.usersIds = usersIds;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="grp_name", nullable=false, length=50)
    public String getGrpName() {
        return this.grpName;
    }
    
    public void setGrpName(String grpName) {
        this.grpName = grpName;
    }

    
    @Column(name="users_ids", nullable=false, length=120)
    public String getUsersIds() {
        return this.usersIds;
    }
    
    public void setUsersIds(String usersIds) {
        this.usersIds = usersIds;
    }




}


