package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * GroupedExams generated by hbm2java
 */
@Entity
@Table(name="grouped_exams"
    ,catalog="villaeducativa"
)
public class GroupedExams  implements java.io.Serializable {


     private Integer id;
     private Integer examGroupId;
     private Integer batchId;

    public GroupedExams() {
    }

    public GroupedExams(Integer examGroupId, Integer batchId) {
       this.examGroupId = examGroupId;
       this.batchId = batchId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="exam_group_id")
    public Integer getExamGroupId() {
        return this.examGroupId;
    }
    
    public void setExamGroupId(Integer examGroupId) {
        this.examGroupId = examGroupId;
    }

    
    @Column(name="batch_id")
    public Integer getBatchId() {
        return this.batchId;
    }
    
    public void setBatchId(Integer batchId) {
        this.batchId = batchId;
    }




}


