package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Hosteldetails generated by hbm2java
 */
@Entity
@Table(name="hosteldetails"
    ,catalog="villaeducativa"
)
public class Hosteldetails  implements java.io.Serializable {


     private Integer id;
     private String hostelName;
     private String address;
     private int isDeleted;

    public Hosteldetails() {
    }

	
    public Hosteldetails(int isDeleted) {
        this.isDeleted = isDeleted;
    }
    public Hosteldetails(String hostelName, String address, int isDeleted) {
       this.hostelName = hostelName;
       this.address = address;
       this.isDeleted = isDeleted;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="hostel_name", length=120)
    public String getHostelName() {
        return this.hostelName;
    }
    
    public void setHostelName(String hostelName) {
        this.hostelName = hostelName;
    }

    
    @Column(name="address", length=120)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="is_deleted", nullable=false)
    public int getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(int isDeleted) {
        this.isDeleted = isDeleted;
    }




}


