package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IndividualPayslipCategories generated by hbm2java
 */
@Entity
@Table(name="individual_payslip_categories"
    ,catalog="villaeducativa"
)
public class IndividualPayslipCategories  implements java.io.Serializable {


     private Integer id;
     private Integer employeeId;
     private Date salaryDate;
     private String name;
     private String amount;
     private Boolean isDeduction;
     private Boolean includeEveryMonth;

    public IndividualPayslipCategories() {
    }

    public IndividualPayslipCategories(Integer employeeId, Date salaryDate, String name, String amount, Boolean isDeduction, Boolean includeEveryMonth) {
       this.employeeId = employeeId;
       this.salaryDate = salaryDate;
       this.name = name;
       this.amount = amount;
       this.isDeduction = isDeduction;
       this.includeEveryMonth = includeEveryMonth;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="employee_id")
    public Integer getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="salary_date", length=10)
    public Date getSalaryDate() {
        return this.salaryDate;
    }
    
    public void setSalaryDate(Date salaryDate) {
        this.salaryDate = salaryDate;
    }

    
    @Column(name="name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="amount")
    public String getAmount() {
        return this.amount;
    }
    
    public void setAmount(String amount) {
        this.amount = amount;
    }

    
    @Column(name="is_deduction")
    public Boolean getIsDeduction() {
        return this.isDeduction;
    }
    
    public void setIsDeduction(Boolean isDeduction) {
        this.isDeduction = isDeduction;
    }

    
    @Column(name="include_every_month")
    public Boolean getIncludeEveryMonth() {
        return this.includeEveryMonth;
    }
    
    public void setIncludeEveryMonth(Boolean includeEveryMonth) {
        this.includeEveryMonth = includeEveryMonth;
    }




}


