package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Logo generated by hbm2java
 */
@Entity
@Table(name="logo"
    ,catalog="villaeducativa"
)
public class Logo  implements java.io.Serializable {


     private Integer id;
     private String photoFileName;
     private String photoContentType;
     private String photoFileSize;
     private byte[] photoData;

    public Logo() {
    }

    public Logo(String photoFileName, String photoContentType, String photoFileSize, byte[] photoData) {
       this.photoFileName = photoFileName;
       this.photoContentType = photoContentType;
       this.photoFileSize = photoFileSize;
       this.photoData = photoData;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="photo_file_name", nullable=false, length=120)
    public String getPhotoFileName() {
        return this.photoFileName;
    }
    
    public void setPhotoFileName(String photoFileName) {
        this.photoFileName = photoFileName;
    }

    
    @Column(name="photo_content_type", nullable=false, length=120)
    public String getPhotoContentType() {
        return this.photoContentType;
    }
    
    public void setPhotoContentType(String photoContentType) {
        this.photoContentType = photoContentType;
    }

    
    @Column(name="photo_file_size", nullable=false, length=120)
    public String getPhotoFileSize() {
        return this.photoFileSize;
    }
    
    public void setPhotoFileSize(String photoFileSize) {
        this.photoFileSize = photoFileSize;
    }

    
    @Column(name="photo_data", nullable=false)
    public byte[] getPhotoData() {
        return this.photoData;
    }
    
    public void setPhotoData(byte[] photoData) {
        this.photoData = photoData;
    }




}


