package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MailboxMessage generated by hbm2java
 */
@Entity
@Table(name="mailbox_message"
    ,catalog="villaeducativa"
)
public class MailboxMessage  implements java.io.Serializable {


     private Integer messageId;
     private int conversationId;
     private int created;
     private int senderId;
     private int recipientId;
     private String text;
     private long crc64;

    public MailboxMessage() {
    }

    public MailboxMessage(int conversationId, int created, int senderId, int recipientId, String text, long crc64) {
       this.conversationId = conversationId;
       this.created = created;
       this.senderId = senderId;
       this.recipientId = recipientId;
       this.text = text;
       this.crc64 = crc64;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="message_id", unique=true, nullable=false)
    public Integer getMessageId() {
        return this.messageId;
    }
    
    public void setMessageId(Integer messageId) {
        this.messageId = messageId;
    }

    
    @Column(name="conversation_id", nullable=false)
    public int getConversationId() {
        return this.conversationId;
    }
    
    public void setConversationId(int conversationId) {
        this.conversationId = conversationId;
    }

    
    @Column(name="created", nullable=false)
    public int getCreated() {
        return this.created;
    }
    
    public void setCreated(int created) {
        this.created = created;
    }

    
    @Column(name="sender_id", nullable=false)
    public int getSenderId() {
        return this.senderId;
    }
    
    public void setSenderId(int senderId) {
        this.senderId = senderId;
    }

    
    @Column(name="recipient_id", nullable=false)
    public int getRecipientId() {
        return this.recipientId;
    }
    
    public void setRecipientId(int recipientId) {
        this.recipientId = recipientId;
    }

    
    @Column(name="text", nullable=false, length=16777215)
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }

    
    @Column(name="crc64", nullable=false)
    public long getCrc64() {
        return this.crc64;
    }
    
    public void setCrc64(long crc64) {
        this.crc64 = crc64;
    }




}


