package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Menu generated by hbm2java
 */
@Entity
@Table(name="menu"
    ,catalog="villaeducativa"
)
public class Menu  implements java.io.Serializable {


     private Byte id;
     private byte parentId;
     private String title;
     private String url;
     private String class_;
     private byte position;
     private byte groupId;

    public Menu() {
    }

    public Menu(byte parentId, String title, String url, String class_, byte position, byte groupId) {
       this.parentId = parentId;
       this.title = title;
       this.url = url;
       this.class_ = class_;
       this.position = position;
       this.groupId = groupId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Byte getId() {
        return this.id;
    }
    
    public void setId(Byte id) {
        this.id = id;
    }

    
    @Column(name="parent_id", nullable=false)
    public byte getParentId() {
        return this.parentId;
    }
    
    public void setParentId(byte parentId) {
        this.parentId = parentId;
    }

    
    @Column(name="title", nullable=false)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="url", nullable=false)
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }

    
    @Column(name="class", nullable=false)
    public String getClass_() {
        return this.class_;
    }
    
    public void setClass_(String class_) {
        this.class_ = class_;
    }

    
    @Column(name="position", nullable=false)
    public byte getPosition() {
        return this.position;
    }
    
    public void setPosition(byte position) {
        this.position = position;
    }

    
    @Column(name="group_id", nullable=false)
    public byte getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(byte groupId) {
        this.groupId = groupId;
    }




}


