package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Messages generated by hbm2java
 */
@Entity
@Table(name="messages"
    ,catalog="villaeducativa"
)
public class Messages  implements java.io.Serializable {


     private Integer id;
     private int senderId;
     private int receiverId;
     private String subject;
     private String body;
     private String isRead;
     private String deletedBy;
     private Date createdAt;

    public Messages() {
    }

	
    public Messages(int senderId, int receiverId, String subject, String isRead, Date createdAt) {
        this.senderId = senderId;
        this.receiverId = receiverId;
        this.subject = subject;
        this.isRead = isRead;
        this.createdAt = createdAt;
    }
    public Messages(int senderId, int receiverId, String subject, String body, String isRead, String deletedBy, Date createdAt) {
       this.senderId = senderId;
       this.receiverId = receiverId;
       this.subject = subject;
       this.body = body;
       this.isRead = isRead;
       this.deletedBy = deletedBy;
       this.createdAt = createdAt;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="sender_id", nullable=false)
    public int getSenderId() {
        return this.senderId;
    }
    
    public void setSenderId(int senderId) {
        this.senderId = senderId;
    }

    
    @Column(name="receiver_id", nullable=false)
    public int getReceiverId() {
        return this.receiverId;
    }
    
    public void setReceiverId(int receiverId) {
        this.receiverId = receiverId;
    }

    
    @Column(name="subject", nullable=false, length=256)
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }

    
    @Column(name="body", length=65535)
    public String getBody() {
        return this.body;
    }
    
    public void setBody(String body) {
        this.body = body;
    }

    
    @Column(name="is_read", nullable=false, length=2)
    public String getIsRead() {
        return this.isRead;
    }
    
    public void setIsRead(String isRead) {
        this.isRead = isRead;
    }

    
    @Column(name="deleted_by", length=8)
    public String getDeletedBy() {
        return this.deletedBy;
    }
    
    public void setDeletedBy(String deletedBy) {
        this.deletedBy = deletedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false, length=19)
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }




}


