package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MessageUser generated by hbm2java
 */
@Entity
@Table(name="message_user"
    ,catalog="villaeducativa"
)
public class MessageUser  implements java.io.Serializable {


     private Integer id;
     private int messageId;
     private String userId;

    public MessageUser() {
    }

    public MessageUser(int messageId, String userId) {
       this.messageId = messageId;
       this.userId = userId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="message_id", nullable=false)
    public int getMessageId() {
        return this.messageId;
    }
    
    public void setMessageId(int messageId) {
        this.messageId = messageId;
    }

    
    @Column(name="user_id", nullable=false, length=120)
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }




}


