package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MessFee generated by hbm2java
 */
@Entity
@Table(name="mess_fee"
    ,catalog="villaeducativa"
)
public class MessFee  implements java.io.Serializable {


     private Integer id;
     private String studentId;
     private String allotmentId;
     private String isPaid;
     private Date created;
     private String status;

    public MessFee() {
    }

	
    public MessFee(String isPaid) {
        this.isPaid = isPaid;
    }
    public MessFee(String studentId, String allotmentId, String isPaid, Date created, String status) {
       this.studentId = studentId;
       this.allotmentId = allotmentId;
       this.isPaid = isPaid;
       this.created = created;
       this.status = status;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="student_id", length=120)
    public String getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(String studentId) {
        this.studentId = studentId;
    }

    
    @Column(name="allotment_id", length=120)
    public String getAllotmentId() {
        return this.allotmentId;
    }
    
    public void setAllotmentId(String allotmentId) {
        this.allotmentId = allotmentId;
    }

    
    @Column(name="is_paid", nullable=false, length=120)
    public String getIsPaid() {
        return this.isPaid;
    }
    
    public void setIsPaid(String isPaid) {
        this.isPaid = isPaid;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="created", length=10)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    
    @Column(name="status", length=120)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


