package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OsTranslated generated by hbm2java
 */
@Entity
@Table(name="os_translated"
    ,catalog="villaeducativa"
)
public class OsTranslated  implements java.io.Serializable {


     private OsTranslatedId id;
     private Sourcemessage sourcemessage;
     private String translation;

    public OsTranslated() {
    }

	
    public OsTranslated(OsTranslatedId id, Sourcemessage sourcemessage) {
        this.id = id;
        this.sourcemessage = sourcemessage;
    }
    public OsTranslated(OsTranslatedId id, Sourcemessage sourcemessage, String translation) {
       this.id = id;
       this.sourcemessage = sourcemessage;
       this.translation = translation;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="id", column=@Column(name="id", nullable=false) ), 
        @AttributeOverride(name="language", column=@Column(name="language", nullable=false, length=16) ) } )
    public OsTranslatedId getId() {
        return this.id;
    }
    
    public void setId(OsTranslatedId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id", nullable=false, insertable=false, updatable=false)
    public Sourcemessage getSourcemessage() {
        return this.sourcemessage;
    }
    
    public void setSourcemessage(Sourcemessage sourcemessage) {
        this.sourcemessage = sourcemessage;
    }

    
    @Column(name="translation", length=65535)
    public String getTranslation() {
        return this.translation;
    }
    
    public void setTranslation(String translation) {
        this.translation = translation;
    }




}


