package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OsTranslatedId generated by hbm2java
 */
@Embeddable
public class OsTranslatedId  implements java.io.Serializable {


     private int id;
     private String language;

    public OsTranslatedId() {
    }

    public OsTranslatedId(int id, String language) {
       this.id = id;
       this.language = language;
    }
   


    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }


    @Column(name="language", nullable=false, length=16)
    public String getLanguage() {
        return this.language;
    }
    
    public void setLanguage(String language) {
        this.language = language;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OsTranslatedId) ) return false;
		 OsTranslatedId castOther = ( OsTranslatedId ) other; 
         
		 return (this.getId()==castOther.getId())
 && ( (this.getLanguage()==castOther.getLanguage()) || ( this.getLanguage()!=null && castOther.getLanguage()!=null && this.getLanguage().equals(castOther.getLanguage()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + ( getLanguage() == null ? 0 : this.getLanguage().hashCode() );
         return result;
   }   


}


