package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PayrollCategories generated by hbm2java
 */
@Entity
@Table(name="payroll_categories"
    ,catalog="villaeducativa"
)
public class PayrollCategories  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Float percentage;
     private Integer payrollCategoryId;
     private Boolean isDeduction;
     private Boolean status;

    public PayrollCategories() {
    }

    public PayrollCategories(String name, Float percentage, Integer payrollCategoryId, Boolean isDeduction, Boolean status) {
       this.name = name;
       this.percentage = percentage;
       this.payrollCategoryId = payrollCategoryId;
       this.isDeduction = isDeduction;
       this.status = status;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="percentage", precision=12, scale=0)
    public Float getPercentage() {
        return this.percentage;
    }
    
    public void setPercentage(Float percentage) {
        this.percentage = percentage;
    }

    
    @Column(name="payroll_category_id")
    public Integer getPayrollCategoryId() {
        return this.payrollCategoryId;
    }
    
    public void setPayrollCategoryId(Integer payrollCategoryId) {
        this.payrollCategoryId = payrollCategoryId;
    }

    
    @Column(name="is_deduction")
    public Boolean getIsDeduction() {
        return this.isDeduction;
    }
    
    public void setIsDeduction(Boolean isDeduction) {
        this.isDeduction = isDeduction;
    }

    
    @Column(name="status")
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }




}


