package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ProfilesFields generated by hbm2java
 */
@Entity
@Table(name="profiles_fields"
    ,catalog="villaeducativa"
)
public class ProfilesFields  implements java.io.Serializable {


     private Integer id;
     private String varname;
     private String title;
     private String fieldType;
     private String fieldSize;
     private String fieldSizeMin;
     private int required;
     private String match;
     private String range;
     private String errorMessage;
     private String otherValidator;
     private String default_;
     private String widget;
     private String widgetparams;
     private int position;
     private int visible;

    public ProfilesFields() {
    }

    public ProfilesFields(String varname, String title, String fieldType, String fieldSize, String fieldSizeMin, int required, String match, String range, String errorMessage, String otherValidator, String default_, String widget, String widgetparams, int position, int visible) {
       this.varname = varname;
       this.title = title;
       this.fieldType = fieldType;
       this.fieldSize = fieldSize;
       this.fieldSizeMin = fieldSizeMin;
       this.required = required;
       this.match = match;
       this.range = range;
       this.errorMessage = errorMessage;
       this.otherValidator = otherValidator;
       this.default_ = default_;
       this.widget = widget;
       this.widgetparams = widgetparams;
       this.position = position;
       this.visible = visible;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="varname", nullable=false, length=50)
    public String getVarname() {
        return this.varname;
    }
    
    public void setVarname(String varname) {
        this.varname = varname;
    }

    
    @Column(name="title", nullable=false)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="field_type", nullable=false, length=50)
    public String getFieldType() {
        return this.fieldType;
    }
    
    public void setFieldType(String fieldType) {
        this.fieldType = fieldType;
    }

    
    @Column(name="field_size", nullable=false, length=15)
    public String getFieldSize() {
        return this.fieldSize;
    }
    
    public void setFieldSize(String fieldSize) {
        this.fieldSize = fieldSize;
    }

    
    @Column(name="field_size_min", nullable=false, length=15)
    public String getFieldSizeMin() {
        return this.fieldSizeMin;
    }
    
    public void setFieldSizeMin(String fieldSizeMin) {
        this.fieldSizeMin = fieldSizeMin;
    }

    
    @Column(name="required", nullable=false)
    public int getRequired() {
        return this.required;
    }
    
    public void setRequired(int required) {
        this.required = required;
    }

    
    @Column(name="match", nullable=false)
    public String getMatch() {
        return this.match;
    }
    
    public void setMatch(String match) {
        this.match = match;
    }

    
    @Column(name="range", nullable=false)
    public String getRange() {
        return this.range;
    }
    
    public void setRange(String range) {
        this.range = range;
    }

    
    @Column(name="error_message", nullable=false)
    public String getErrorMessage() {
        return this.errorMessage;
    }
    
    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
    }

    
    @Column(name="other_validator", nullable=false, length=5000)
    public String getOtherValidator() {
        return this.otherValidator;
    }
    
    public void setOtherValidator(String otherValidator) {
        this.otherValidator = otherValidator;
    }

    
    @Column(name="default", nullable=false)
    public String getDefault_() {
        return this.default_;
    }
    
    public void setDefault_(String default_) {
        this.default_ = default_;
    }

    
    @Column(name="widget", nullable=false)
    public String getWidget() {
        return this.widget;
    }
    
    public void setWidget(String widget) {
        this.widget = widget;
    }

    
    @Column(name="widgetparams", nullable=false, length=5000)
    public String getWidgetparams() {
        return this.widgetparams;
    }
    
    public void setWidgetparams(String widgetparams) {
        this.widgetparams = widgetparams;
    }

    
    @Column(name="position", nullable=false)
    public int getPosition() {
        return this.position;
    }
    
    public void setPosition(int position) {
        this.position = position;
    }

    
    @Column(name="visible", nullable=false)
    public int getVisible() {
        return this.visible;
    }
    
    public void setVisible(int visible) {
        this.visible = visible;
    }




}


