package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Publication generated by hbm2java
 */
@Entity
@Table(name="publication"
    ,catalog="villaeducativa"
)
public class Publication  implements java.io.Serializable {


     private Integer publicationId;
     private String name;
     private String location;

    public Publication() {
    }

    public Publication(String name, String location) {
       this.name = name;
       this.location = location;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="publication_id", unique=true, nullable=false)
    public Integer getPublicationId() {
        return this.publicationId;
    }
    
    public void setPublicationId(Integer publicationId) {
        this.publicationId = publicationId;
    }

    
    @Column(name="name", length=120)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="location", length=120)
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }




}


