package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ReturnBook generated by hbm2java
 */
@Entity
@Table(name="return_book"
    ,catalog="villaeducativa"
)
public class ReturnBook  implements java.io.Serializable {


     private Integer id;
     private String studentId;
     private String bookId;
     private String borrowBookId;
     private Date issueDate;
     private Date returnDate;
     private Date createdDate;
     private String status;

    public ReturnBook() {
    }

    public ReturnBook(String studentId, String bookId, String borrowBookId, Date issueDate, Date returnDate, Date createdDate, String status) {
       this.studentId = studentId;
       this.bookId = bookId;
       this.borrowBookId = borrowBookId;
       this.issueDate = issueDate;
       this.returnDate = returnDate;
       this.createdDate = createdDate;
       this.status = status;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="student_id", length=120)
    public String getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(String studentId) {
        this.studentId = studentId;
    }

    
    @Column(name="book_id", length=120)
    public String getBookId() {
        return this.bookId;
    }
    
    public void setBookId(String bookId) {
        this.bookId = bookId;
    }

    
    @Column(name="borrow_book_id", length=120)
    public String getBorrowBookId() {
        return this.borrowBookId;
    }
    
    public void setBorrowBookId(String borrowBookId) {
        this.borrowBookId = borrowBookId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="issue_date", length=10)
    public Date getIssueDate() {
        return this.issueDate;
    }
    
    public void setIssueDate(Date issueDate) {
        this.issueDate = issueDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="return_date", length=10)
    public Date getReturnDate() {
        return this.returnDate;
    }
    
    public void setReturnDate(Date returnDate) {
        this.returnDate = returnDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="created_date", length=10)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="status", length=120)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


