package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Rights generated by hbm2java
 */
@Entity
@Table(name="rights"
    ,catalog="villaeducativa"
)
public class Rights  implements java.io.Serializable {


     private String itemname;
     private Authitem authitem;
     private int type;
     private int weight;

    public Rights() {
    }

    public Rights(Authitem authitem, int type, int weight) {
       this.authitem = authitem;
       this.type = type;
       this.weight = weight;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="authitem"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="itemname", unique=true, nullable=false, length=64)
    public String getItemname() {
        return this.itemname;
    }
    
    public void setItemname(String itemname) {
        this.itemname = itemname;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Authitem getAuthitem() {
        return this.authitem;
    }
    
    public void setAuthitem(Authitem authitem) {
        this.authitem = authitem;
    }

    
    @Column(name="type", nullable=false)
    public int getType() {
        return this.type;
    }
    
    public void setType(int type) {
        this.type = type;
    }

    
    @Column(name="weight", nullable=false)
    public int getWeight() {
        return this.weight;
    }
    
    public void setWeight(int weight) {
        this.weight = weight;
    }




}


