package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RoomDetails generated by hbm2java
 */
@Entity
@Table(name="room_details"
    ,catalog="villaeducativa"
)
public class RoomDetails  implements java.io.Serializable {


     private Integer id;
     private String roomNo;
     private String bedNo;
     private String noOfFloors;
     private String modeOfAllotment;
     private Date created;
     private String status;
     private String studentId;

    public RoomDetails() {
    }

    public RoomDetails(String roomNo, String bedNo, String noOfFloors, String modeOfAllotment, Date created, String status, String studentId) {
       this.roomNo = roomNo;
       this.bedNo = bedNo;
       this.noOfFloors = noOfFloors;
       this.modeOfAllotment = modeOfAllotment;
       this.created = created;
       this.status = status;
       this.studentId = studentId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="room_no", length=120)
    public String getRoomNo() {
        return this.roomNo;
    }
    
    public void setRoomNo(String roomNo) {
        this.roomNo = roomNo;
    }

    
    @Column(name="bed_no", length=120)
    public String getBedNo() {
        return this.bedNo;
    }
    
    public void setBedNo(String bedNo) {
        this.bedNo = bedNo;
    }

    
    @Column(name="no_of_floors", length=120)
    public String getNoOfFloors() {
        return this.noOfFloors;
    }
    
    public void setNoOfFloors(String noOfFloors) {
        this.noOfFloors = noOfFloors;
    }

    
    @Column(name="mode_of_allotment", length=120)
    public String getModeOfAllotment() {
        return this.modeOfAllotment;
    }
    
    public void setModeOfAllotment(String modeOfAllotment) {
        this.modeOfAllotment = modeOfAllotment;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="created", length=10)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    
    @Column(name="status", length=120)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="student_id", length=120)
    public String getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(String studentId) {
        this.studentId = studentId;
    }




}


