package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RouteDetails generated by hbm2java
 */
@Entity
@Table(name="route_details"
    ,catalog="villaeducativa"
)
public class RouteDetails  implements java.io.Serializable {


     private Integer id;
     private String routeName;
     private String noOfStops;
     private String vehicleId;

    public RouteDetails() {
    }

    public RouteDetails(String routeName, String noOfStops, String vehicleId) {
       this.routeName = routeName;
       this.noOfStops = noOfStops;
       this.vehicleId = vehicleId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="route_name", length=120)
    public String getRouteName() {
        return this.routeName;
    }
    
    public void setRouteName(String routeName) {
        this.routeName = routeName;
    }

    
    @Column(name="no_of_stops", length=120)
    public String getNoOfStops() {
        return this.noOfStops;
    }
    
    public void setNoOfStops(String noOfStops) {
        this.noOfStops = noOfStops;
    }

    
    @Column(name="vehicle_id", length=120)
    public String getVehicleId() {
        return this.vehicleId;
    }
    
    public void setVehicleId(String vehicleId) {
        this.vehicleId = vehicleId;
    }




}


