package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SmsSettings generated by hbm2java
 */
@Entity
@Table(name="sms_settings"
    ,catalog="villaeducativa"
)
public class SmsSettings  implements java.io.Serializable {


     private Integer id;
     private String settingsKey;
     private Boolean isEnabled;

    public SmsSettings() {
    }

    public SmsSettings(String settingsKey, Boolean isEnabled) {
       this.settingsKey = settingsKey;
       this.isEnabled = isEnabled;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="settings_key")
    public String getSettingsKey() {
        return this.settingsKey;
    }
    
    public void setSettingsKey(String settingsKey) {
        this.settingsKey = settingsKey;
    }

    
    @Column(name="is_enabled")
    public Boolean getIsEnabled() {
        return this.isEnabled;
    }
    
    public void setIsEnabled(Boolean isEnabled) {
        this.isEnabled = isEnabled;
    }




}


