package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sourcemessage generated by hbm2java
 */
@Entity
@Table(name="sourcemessage"
    ,catalog="villaeducativa"
)
public class Sourcemessage  implements java.io.Serializable {


     private Integer id;
     private String category;
     private String message;
     private Set<OsTranslated> osTranslateds = new HashSet<OsTranslated>(0);

    public Sourcemessage() {
    }

    public Sourcemessage(String category, String message, Set<OsTranslated> osTranslateds) {
       this.category = category;
       this.message = message;
       this.osTranslateds = osTranslateds;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="category", length=32)
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }

    
    @Column(name="message", length=65535)
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="sourcemessage")
    public Set<OsTranslated> getOsTranslateds() {
        return this.osTranslateds;
    }
    
    public void setOsTranslateds(Set<OsTranslated> osTranslateds) {
        this.osTranslateds = osTranslateds;
    }




}


