package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StopDetails generated by hbm2java
 */
@Entity
@Table(name="stop_details"
    ,catalog="villaeducativa"
)
public class StopDetails  implements java.io.Serializable {


     private Integer id;
     private Integer routeId;
     private String stopName;
     private String fare;
     private Date arrivalMrng;
     private Date departureMrng;
     private Date arrivalEvng;
     private Date departureEvng;

    public StopDetails() {
    }

    public StopDetails(Integer routeId, String stopName, String fare, Date arrivalMrng, Date departureMrng, Date arrivalEvng, Date departureEvng) {
       this.routeId = routeId;
       this.stopName = stopName;
       this.fare = fare;
       this.arrivalMrng = arrivalMrng;
       this.departureMrng = departureMrng;
       this.arrivalEvng = arrivalEvng;
       this.departureEvng = departureEvng;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="route_id")
    public Integer getRouteId() {
        return this.routeId;
    }
    
    public void setRouteId(Integer routeId) {
        this.routeId = routeId;
    }

    
    @Column(name="stop_name", length=120)
    public String getStopName() {
        return this.stopName;
    }
    
    public void setStopName(String stopName) {
        this.stopName = stopName;
    }

    
    @Column(name="fare", length=120)
    public String getFare() {
        return this.fare;
    }
    
    public void setFare(String fare) {
        this.fare = fare;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="arrival_mrng", length=8)
    public Date getArrivalMrng() {
        return this.arrivalMrng;
    }
    
    public void setArrivalMrng(Date arrivalMrng) {
        this.arrivalMrng = arrivalMrng;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="departure_mrng", length=8)
    public Date getDepartureMrng() {
        return this.departureMrng;
    }
    
    public void setDepartureMrng(Date departureMrng) {
        this.departureMrng = departureMrng;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="arrival_evng", length=8)
    public Date getArrivalEvng() {
        return this.arrivalEvng;
    }
    
    public void setArrivalEvng(Date arrivalEvng) {
        this.arrivalEvng = arrivalEvng;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="departure_evng", length=8)
    public Date getDepartureEvng() {
        return this.departureEvng;
    }
    
    public void setDepartureEvng(Date departureEvng) {
        this.departureEvng = departureEvng;
    }




}


