package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * StoreCategory generated by hbm2java
 */
@Entity
@Table(name="store_category"
    ,catalog="villaeducativa"
)
public class StoreCategory  implements java.io.Serializable {


     private Integer caId;
     private String caName;
     private Integer status;

    public StoreCategory() {
    }

	
    public StoreCategory(String caName) {
        this.caName = caName;
    }
    public StoreCategory(String caName, Integer status) {
       this.caName = caName;
       this.status = status;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ca_id", unique=true, nullable=false)
    public Integer getCaId() {
        return this.caId;
    }
    
    public void setCaId(Integer caId) {
        this.caId = caId;
    }

    
    @Column(name="ca_name", nullable=false, length=200)
    public String getCaName() {
        return this.caName;
    }
    
    public void setCaName(String caName) {
        this.caName = caName;
    }

    
    @Column(name="status")
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }




}


