package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * StudentPreviousDatas generated by hbm2java
 */
@Entity
@Table(name="student_previous_datas"
    ,catalog="villaeducativa"
)
public class StudentPreviousDatas  implements java.io.Serializable {


     private Integer id;
     private Integer studentId;
     private String institution;
     private String year;
     private String course;
     private String totalMark;

    public StudentPreviousDatas() {
    }

    public StudentPreviousDatas(Integer studentId, String institution, String year, String course, String totalMark) {
       this.studentId = studentId;
       this.institution = institution;
       this.year = year;
       this.course = course;
       this.totalMark = totalMark;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="student_id")
    public Integer getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    
    @Column(name="institution")
    public String getInstitution() {
        return this.institution;
    }
    
    public void setInstitution(String institution) {
        this.institution = institution;
    }

    
    @Column(name="year")
    public String getYear() {
        return this.year;
    }
    
    public void setYear(String year) {
        this.year = year;
    }

    
    @Column(name="course")
    public String getCourse() {
        return this.course;
    }
    
    public void setCourse(String course) {
        this.course = course;
    }

    
    @Column(name="total_mark")
    public String getTotalMark() {
        return this.totalMark;
    }
    
    public void setTotalMark(String totalMark) {
        this.totalMark = totalMark;
    }




}


