package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * StudentPreviousSubjectMarks generated by hbm2java
 */
@Entity
@Table(name="student_previous_subject_marks"
    ,catalog="villaeducativa"
)
public class StudentPreviousSubjectMarks  implements java.io.Serializable {


     private Integer id;
     private Integer studentId;
     private String subject;
     private String mark;

    public StudentPreviousSubjectMarks() {
    }

    public StudentPreviousSubjectMarks(Integer studentId, String subject, String mark) {
       this.studentId = studentId;
       this.subject = subject;
       this.mark = mark;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="student_id")
    public Integer getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    
    @Column(name="subject")
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }

    
    @Column(name="mark")
    public String getMark() {
        return this.mark;
    }
    
    public void setMark(String mark) {
        this.mark = mark;
    }




}


