package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * StudentExtra generated by hbm2java
 */
@Entity
@Table(name="student_extra"
    ,catalog="villaeducativa"
)
public class StudentExtra  implements java.io.Serializable {


     private Integer id;
     private int studentId;
     private String extra;

    public StudentExtra() {
    }

    public StudentExtra(int studentId, String extra) {
       this.studentId = studentId;
       this.extra = extra;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="student_id", nullable=false)
    public int getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(int studentId) {
        this.studentId = studentId;
    }

    
    @Column(name="extra", nullable=false, length=65535)
    public String getExtra() {
        return this.extra;
    }
    
    public void setExtra(String extra) {
        this.extra = extra;
    }




}


