package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Students generated by hbm2java
 */
@Entity
@Table(name="students"
    ,catalog="villaeducativa"
)
public class Students  implements java.io.Serializable {


     private Integer id;
     private int uid;
     private int parentId;
     private String admissionNo;
     private String classRollNo;
     private Date admissionDate;
     private String firstName;
     private String middleName;
     private String lastName;
     private Integer batchId;
     private Date dateOfBirth;
     private String gender;
     private String bloodGroup;
     private String birthPlace;
     private Integer nationalityId;
     private String language;
     private String religion;
     private Integer studentCategoryId;
     private String addressLine1;
     private String addressLine2;
     private String city;
     private String state;
     private String pinCode;
     private Integer countryId;
     private String phone1;
     private String phone2;
     private String email;
     private Integer immediateContactId;
     private Boolean isSmsEnabled;
     private String photoFileName;
     private String photoContentType;
     private byte[] photoData;
     private String statusDescription;
     private Boolean isActive;
     private Boolean isDeleted;
     private Date createdAt;
     private Date updatedAt;
     private Boolean hasPaidFees;
     private Integer photoFileSize;
     private Integer userId;

    public Students() {
    }

	
    public Students(int uid, int parentId) {
        this.uid = uid;
        this.parentId = parentId;
    }
    public Students(int uid, int parentId, String admissionNo, String classRollNo, Date admissionDate, String firstName, String middleName, String lastName, Integer batchId, Date dateOfBirth, String gender, String bloodGroup, String birthPlace, Integer nationalityId, String language, String religion, Integer studentCategoryId, String addressLine1, String addressLine2, String city, String state, String pinCode, Integer countryId, String phone1, String phone2, String email, Integer immediateContactId, Boolean isSmsEnabled, String photoFileName, String photoContentType, byte[] photoData, String statusDescription, Boolean isActive, Boolean isDeleted, Date createdAt, Date updatedAt, Boolean hasPaidFees, Integer photoFileSize, Integer userId) {
       this.uid = uid;
       this.parentId = parentId;
       this.admissionNo = admissionNo;
       this.classRollNo = classRollNo;
       this.admissionDate = admissionDate;
       this.firstName = firstName;
       this.middleName = middleName;
       this.lastName = lastName;
       this.batchId = batchId;
       this.dateOfBirth = dateOfBirth;
       this.gender = gender;
       this.bloodGroup = bloodGroup;
       this.birthPlace = birthPlace;
       this.nationalityId = nationalityId;
       this.language = language;
       this.religion = religion;
       this.studentCategoryId = studentCategoryId;
       this.addressLine1 = addressLine1;
       this.addressLine2 = addressLine2;
       this.city = city;
       this.state = state;
       this.pinCode = pinCode;
       this.countryId = countryId;
       this.phone1 = phone1;
       this.phone2 = phone2;
       this.email = email;
       this.immediateContactId = immediateContactId;
       this.isSmsEnabled = isSmsEnabled;
       this.photoFileName = photoFileName;
       this.photoContentType = photoContentType;
       this.photoData = photoData;
       this.statusDescription = statusDescription;
       this.isActive = isActive;
       this.isDeleted = isDeleted;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.hasPaidFees = hasPaidFees;
       this.photoFileSize = photoFileSize;
       this.userId = userId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="uid", nullable=false)
    public int getUid() {
        return this.uid;
    }
    
    public void setUid(int uid) {
        this.uid = uid;
    }

    
    @Column(name="parent_id", nullable=false)
    public int getParentId() {
        return this.parentId;
    }
    
    public void setParentId(int parentId) {
        this.parentId = parentId;
    }

    
    @Column(name="admission_no")
    public String getAdmissionNo() {
        return this.admissionNo;
    }
    
    public void setAdmissionNo(String admissionNo) {
        this.admissionNo = admissionNo;
    }

    
    @Column(name="class_roll_no")
    public String getClassRollNo() {
        return this.classRollNo;
    }
    
    public void setClassRollNo(String classRollNo) {
        this.classRollNo = classRollNo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="admission_date", length=10)
    public Date getAdmissionDate() {
        return this.admissionDate;
    }
    
    public void setAdmissionDate(Date admissionDate) {
        this.admissionDate = admissionDate;
    }

    
    @Column(name="first_name")
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="middle_name")
    public String getMiddleName() {
        return this.middleName;
    }
    
    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }

    
    @Column(name="last_name")
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="batch_id")
    public Integer getBatchId() {
        return this.batchId;
    }
    
    public void setBatchId(Integer batchId) {
        this.batchId = batchId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_of_birth", length=10)
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    
    @Column(name="gender")
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }

    
    @Column(name="blood_group")
    public String getBloodGroup() {
        return this.bloodGroup;
    }
    
    public void setBloodGroup(String bloodGroup) {
        this.bloodGroup = bloodGroup;
    }

    
    @Column(name="birth_place")
    public String getBirthPlace() {
        return this.birthPlace;
    }
    
    public void setBirthPlace(String birthPlace) {
        this.birthPlace = birthPlace;
    }

    
    @Column(name="nationality_id")
    public Integer getNationalityId() {
        return this.nationalityId;
    }
    
    public void setNationalityId(Integer nationalityId) {
        this.nationalityId = nationalityId;
    }

    
    @Column(name="language")
    public String getLanguage() {
        return this.language;
    }
    
    public void setLanguage(String language) {
        this.language = language;
    }

    
    @Column(name="religion")
    public String getReligion() {
        return this.religion;
    }
    
    public void setReligion(String religion) {
        this.religion = religion;
    }

    
    @Column(name="student_category_id")
    public Integer getStudentCategoryId() {
        return this.studentCategoryId;
    }
    
    public void setStudentCategoryId(Integer studentCategoryId) {
        this.studentCategoryId = studentCategoryId;
    }

    
    @Column(name="address_line1")
    public String getAddressLine1() {
        return this.addressLine1;
    }
    
    public void setAddressLine1(String addressLine1) {
        this.addressLine1 = addressLine1;
    }

    
    @Column(name="address_line2")
    public String getAddressLine2() {
        return this.addressLine2;
    }
    
    public void setAddressLine2(String addressLine2) {
        this.addressLine2 = addressLine2;
    }

    
    @Column(name="city")
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="state")
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }

    
    @Column(name="pin_code")
    public String getPinCode() {
        return this.pinCode;
    }
    
    public void setPinCode(String pinCode) {
        this.pinCode = pinCode;
    }

    
    @Column(name="country_id")
    public Integer getCountryId() {
        return this.countryId;
    }
    
    public void setCountryId(Integer countryId) {
        this.countryId = countryId;
    }

    
    @Column(name="phone1")
    public String getPhone1() {
        return this.phone1;
    }
    
    public void setPhone1(String phone1) {
        this.phone1 = phone1;
    }

    
    @Column(name="phone2")
    public String getPhone2() {
        return this.phone2;
    }
    
    public void setPhone2(String phone2) {
        this.phone2 = phone2;
    }

    
    @Column(name="email")
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="immediate_contact_id")
    public Integer getImmediateContactId() {
        return this.immediateContactId;
    }
    
    public void setImmediateContactId(Integer immediateContactId) {
        this.immediateContactId = immediateContactId;
    }

    
    @Column(name="is_sms_enabled")
    public Boolean getIsSmsEnabled() {
        return this.isSmsEnabled;
    }
    
    public void setIsSmsEnabled(Boolean isSmsEnabled) {
        this.isSmsEnabled = isSmsEnabled;
    }

    
    @Column(name="photo_file_name")
    public String getPhotoFileName() {
        return this.photoFileName;
    }
    
    public void setPhotoFileName(String photoFileName) {
        this.photoFileName = photoFileName;
    }

    
    @Column(name="photo_content_type")
    public String getPhotoContentType() {
        return this.photoContentType;
    }
    
    public void setPhotoContentType(String photoContentType) {
        this.photoContentType = photoContentType;
    }

    
    @Column(name="photo_data")
    public byte[] getPhotoData() {
        return this.photoData;
    }
    
    public void setPhotoData(byte[] photoData) {
        this.photoData = photoData;
    }

    
    @Column(name="status_description")
    public String getStatusDescription() {
        return this.statusDescription;
    }
    
    public void setStatusDescription(String statusDescription) {
        this.statusDescription = statusDescription;
    }

    
    @Column(name="is_active")
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    
    @Column(name="is_deleted")
    public Boolean getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", length=19)
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at", length=19)
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    
    @Column(name="has_paid_fees")
    public Boolean getHasPaidFees() {
        return this.hasPaidFees;
    }
    
    public void setHasPaidFees(Boolean hasPaidFees) {
        this.hasPaidFees = hasPaidFees;
    }

    
    @Column(name="photo_file_size")
    public Integer getPhotoFileSize() {
        return this.photoFileSize;
    }
    
    public void setPhotoFileSize(Integer photoFileSize) {
        this.photoFileSize = photoFileSize;
    }

    
    @Column(name="user_id")
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }




}


