package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * StudentAdditionalDetails generated by hbm2java
 */
@Entity
@Table(name="student_additional_details"
    ,catalog="villaeducativa"
)
public class StudentAdditionalDetails  implements java.io.Serializable {


     private Integer id;
     private Integer studentId;
     private Integer additionalFieldId;
     private String additionalInfo;

    public StudentAdditionalDetails() {
    }

    public StudentAdditionalDetails(Integer studentId, Integer additionalFieldId, String additionalInfo) {
       this.studentId = studentId;
       this.additionalFieldId = additionalFieldId;
       this.additionalInfo = additionalInfo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="student_id")
    public Integer getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    
    @Column(name="additional_field_id")
    public Integer getAdditionalFieldId() {
        return this.additionalFieldId;
    }
    
    public void setAdditionalFieldId(Integer additionalFieldId) {
        this.additionalFieldId = additionalFieldId;
    }

    
    @Column(name="additional_info")
    public String getAdditionalInfo() {
        return this.additionalInfo;
    }
    
    public void setAdditionalInfo(String additionalInfo) {
        this.additionalInfo = additionalInfo;
    }




}


