package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * StudentGuardian generated by hbm2java
 */
@Entity
@Table(name="student_guardian"
    ,catalog="villaeducativa"
)
public class StudentGuardian  implements java.io.Serializable {


     private Integer id;
     private int gid;
     private int sid;

    public StudentGuardian() {
    }

    public StudentGuardian(int gid, int sid) {
       this.gid = gid;
       this.sid = sid;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="gid", nullable=false)
    public int getGid() {
        return this.gid;
    }
    
    public void setGid(int gid) {
        this.gid = gid;
    }

    
    @Column(name="sid", nullable=false)
    public int getSid() {
        return this.sid;
    }
    
    public void setSid(int sid) {
        this.sid = sid;
    }




}


