package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TimetableEntries generated by hbm2java
 */
@Entity
@Table(name="timetable_entries"
    ,catalog="villaeducativa"
)
public class TimetableEntries  implements java.io.Serializable {


     private Integer id;
     private Integer batchId;
     private Integer weekdayId;
     private Integer classTimingId;
     private Integer subjectId;
     private Integer employeeId;

    public TimetableEntries() {
    }

    public TimetableEntries(Integer batchId, Integer weekdayId, Integer classTimingId, Integer subjectId, Integer employeeId) {
       this.batchId = batchId;
       this.weekdayId = weekdayId;
       this.classTimingId = classTimingId;
       this.subjectId = subjectId;
       this.employeeId = employeeId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="batch_id")
    public Integer getBatchId() {
        return this.batchId;
    }
    
    public void setBatchId(Integer batchId) {
        this.batchId = batchId;
    }

    
    @Column(name="weekday_id")
    public Integer getWeekdayId() {
        return this.weekdayId;
    }
    
    public void setWeekdayId(Integer weekdayId) {
        this.weekdayId = weekdayId;
    }

    
    @Column(name="class_timing_id")
    public Integer getClassTimingId() {
        return this.classTimingId;
    }
    
    public void setClassTimingId(Integer classTimingId) {
        this.classTimingId = classTimingId;
    }

    
    @Column(name="subject_id")
    public Integer getSubjectId() {
        return this.subjectId;
    }
    
    public void setSubjectId(Integer subjectId) {
        this.subjectId = subjectId;
    }

    
    @Column(name="employee_id")
    public Integer getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }




}


