package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserSettings generated by hbm2java
 */
@Entity
@Table(name="user_settings"
    ,catalog="villaeducativa"
)
public class UserSettings  implements java.io.Serializable {


     private Integer id;
     private String userId;
     private String dateformat;
     private String displaydate;
     private String timezone;
     private String timeformat;
     private String nameFormat;
     private String language;

    public UserSettings() {
    }

    public UserSettings(String userId, String dateformat, String displaydate, String timezone, String timeformat, String nameFormat, String language) {
       this.userId = userId;
       this.dateformat = dateformat;
       this.displaydate = displaydate;
       this.timezone = timezone;
       this.timeformat = timeformat;
       this.nameFormat = nameFormat;
       this.language = language;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="user_id", length=120)
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }

    
    @Column(name="dateformat", length=120)
    public String getDateformat() {
        return this.dateformat;
    }
    
    public void setDateformat(String dateformat) {
        this.dateformat = dateformat;
    }

    
    @Column(name="displaydate", length=120)
    public String getDisplaydate() {
        return this.displaydate;
    }
    
    public void setDisplaydate(String displaydate) {
        this.displaydate = displaydate;
    }

    
    @Column(name="timezone", length=120)
    public String getTimezone() {
        return this.timezone;
    }
    
    public void setTimezone(String timezone) {
        this.timezone = timezone;
    }

    
    @Column(name="timeformat", length=120)
    public String getTimeformat() {
        return this.timeformat;
    }
    
    public void setTimeformat(String timeformat) {
        this.timeformat = timeformat;
    }

    
    @Column(name="name_format", length=120)
    public String getNameFormat() {
        return this.nameFormat;
    }
    
    public void setNameFormat(String nameFormat) {
        this.nameFormat = nameFormat;
    }

    
    @Column(name="language", length=120)
    public String getLanguage() {
        return this.language;
    }
    
    public void setLanguage(String language) {
        this.language = language;
    }




}


