package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserDetails generated by hbm2java
 */
@Entity
@Table(name="user_details"
    ,catalog="villaeducativa"
)
public class UserDetails  implements java.io.Serializable {


     private Integer id;
     private int userId;
     private Integer agencyEmployeeId;
     private String lastname;
     private String firstname;
     private String suffix;
     private String address1;
     private String address2;
     private Integer zipCode;
     private String city;
     private String state;
     private Integer phone1;
     private Integer phone2;
     private Date dob;
     private Integer ssn;
     private String includepayroll;
     private String employeeType;
     private String weekendAccess;
     private Date earliestLoginTime;
     private Date automaticLodoutTime;
     private Date hireDate;
     private Date terminationDate;
     private String file;
     private String attachment;
     private String photo;
     private String photoThumb;
     private String sign;

    public UserDetails() {
    }

	
    public UserDetails(int userId, String lastname, String firstname, String suffix) {
        this.userId = userId;
        this.lastname = lastname;
        this.firstname = firstname;
        this.suffix = suffix;
    }
    public UserDetails(int userId, Integer agencyEmployeeId, String lastname, String firstname, String suffix, String address1, String address2, Integer zipCode, String city, String state, Integer phone1, Integer phone2, Date dob, Integer ssn, String includepayroll, String employeeType, String weekendAccess, Date earliestLoginTime, Date automaticLodoutTime, Date hireDate, Date terminationDate, String file, String attachment, String photo, String photoThumb, String sign) {
       this.userId = userId;
       this.agencyEmployeeId = agencyEmployeeId;
       this.lastname = lastname;
       this.firstname = firstname;
       this.suffix = suffix;
       this.address1 = address1;
       this.address2 = address2;
       this.zipCode = zipCode;
       this.city = city;
       this.state = state;
       this.phone1 = phone1;
       this.phone2 = phone2;
       this.dob = dob;
       this.ssn = ssn;
       this.includepayroll = includepayroll;
       this.employeeType = employeeType;
       this.weekendAccess = weekendAccess;
       this.earliestLoginTime = earliestLoginTime;
       this.automaticLodoutTime = automaticLodoutTime;
       this.hireDate = hireDate;
       this.terminationDate = terminationDate;
       this.file = file;
       this.attachment = attachment;
       this.photo = photo;
       this.photoThumb = photoThumb;
       this.sign = sign;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="user_id", nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }

    
    @Column(name="agency_employee_id")
    public Integer getAgencyEmployeeId() {
        return this.agencyEmployeeId;
    }
    
    public void setAgencyEmployeeId(Integer agencyEmployeeId) {
        this.agencyEmployeeId = agencyEmployeeId;
    }

    
    @Column(name="lastname", nullable=false, length=120)
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    
    @Column(name="firstname", nullable=false, length=120)
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    
    @Column(name="suffix", nullable=false, length=120)
    public String getSuffix() {
        return this.suffix;
    }
    
    public void setSuffix(String suffix) {
        this.suffix = suffix;
    }

    
    @Column(name="address1", length=120)
    public String getAddress1() {
        return this.address1;
    }
    
    public void setAddress1(String address1) {
        this.address1 = address1;
    }

    
    @Column(name="address2", length=120)
    public String getAddress2() {
        return this.address2;
    }
    
    public void setAddress2(String address2) {
        this.address2 = address2;
    }

    
    @Column(name="zip_code")
    public Integer getZipCode() {
        return this.zipCode;
    }
    
    public void setZipCode(Integer zipCode) {
        this.zipCode = zipCode;
    }

    
    @Column(name="city", length=120)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="state", length=120)
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }

    
    @Column(name="phone1")
    public Integer getPhone1() {
        return this.phone1;
    }
    
    public void setPhone1(Integer phone1) {
        this.phone1 = phone1;
    }

    
    @Column(name="phone2")
    public Integer getPhone2() {
        return this.phone2;
    }
    
    public void setPhone2(Integer phone2) {
        this.phone2 = phone2;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dob", length=19)
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }

    
    @Column(name="ssn")
    public Integer getSsn() {
        return this.ssn;
    }
    
    public void setSsn(Integer ssn) {
        this.ssn = ssn;
    }

    
    @Column(name="includepayroll", length=120)
    public String getIncludepayroll() {
        return this.includepayroll;
    }
    
    public void setIncludepayroll(String includepayroll) {
        this.includepayroll = includepayroll;
    }

    
    @Column(name="employee_type", length=120)
    public String getEmployeeType() {
        return this.employeeType;
    }
    
    public void setEmployeeType(String employeeType) {
        this.employeeType = employeeType;
    }

    
    @Column(name="weekend_access", length=120)
    public String getWeekendAccess() {
        return this.weekendAccess;
    }
    
    public void setWeekendAccess(String weekendAccess) {
        this.weekendAccess = weekendAccess;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="earliest_login_time", length=8)
    public Date getEarliestLoginTime() {
        return this.earliestLoginTime;
    }
    
    public void setEarliestLoginTime(Date earliestLoginTime) {
        this.earliestLoginTime = earliestLoginTime;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="automatic_lodout_time", length=8)
    public Date getAutomaticLodoutTime() {
        return this.automaticLodoutTime;
    }
    
    public void setAutomaticLodoutTime(Date automaticLodoutTime) {
        this.automaticLodoutTime = automaticLodoutTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="hire_date", length=19)
    public Date getHireDate() {
        return this.hireDate;
    }
    
    public void setHireDate(Date hireDate) {
        this.hireDate = hireDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="termination_date", length=19)
    public Date getTerminationDate() {
        return this.terminationDate;
    }
    
    public void setTerminationDate(Date terminationDate) {
        this.terminationDate = terminationDate;
    }

    
    @Column(name="File", length=256)
    public String getFile() {
        return this.file;
    }
    
    public void setFile(String file) {
        this.file = file;
    }

    
    @Column(name="attachment", length=256)
    public String getAttachment() {
        return this.attachment;
    }
    
    public void setAttachment(String attachment) {
        this.attachment = attachment;
    }

    
    @Column(name="photo", length=256)
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }

    
    @Column(name="photo_thumb")
    public String getPhotoThumb() {
        return this.photoThumb;
    }
    
    public void setPhotoThumb(String photoThumb) {
        this.photoThumb = photoThumb;
    }

    
    @Column(name="sign", length=120)
    public String getSign() {
        return this.sign;
    }
    
    public void setSign(String sign) {
        this.sign = sign;
    }




}


