package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Vacate generated by hbm2java
 */
@Entity
@Table(name="vacate"
    ,catalog="villaeducativa"
)
public class Vacate  implements java.io.Serializable {


     private Integer id;
     private Integer studentId;
     private String roomNo;
     private String allotId;
     private String status;
     private Date admitDate;
     private Date vacateDate;

    public Vacate() {
    }

    public Vacate(Integer studentId, String roomNo, String allotId, String status, Date admitDate, Date vacateDate) {
       this.studentId = studentId;
       this.roomNo = roomNo;
       this.allotId = allotId;
       this.status = status;
       this.admitDate = admitDate;
       this.vacateDate = vacateDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="student_id")
    public Integer getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    
    @Column(name="room_no", length=120)
    public String getRoomNo() {
        return this.roomNo;
    }
    
    public void setRoomNo(String roomNo) {
        this.roomNo = roomNo;
    }

    
    @Column(name="allot_id", length=120)
    public String getAllotId() {
        return this.allotId;
    }
    
    public void setAllotId(String allotId) {
        this.allotId = allotId;
    }

    
    @Column(name="status", length=120)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="admit_date", length=10)
    public Date getAdmitDate() {
        return this.admitDate;
    }
    
    public void setAdmitDate(Date admitDate) {
        this.admitDate = admitDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="vacate_date", length=10)
    public Date getVacateDate() {
        return this.vacateDate;
    }
    
    public void setVacateDate(Date vacateDate) {
        this.vacateDate = vacateDate;
    }




}


