package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * VehicleDetails generated by hbm2java
 */
@Entity
@Table(name="vehicle_details"
    ,catalog="villaeducativa"
)
public class VehicleDetails  implements java.io.Serializable {


     private Integer id;
     private String vehicleNo;
     private String vehicleCode;
     private String noOfSeats;
     private String maximumCapacity;
     private String vehicleType;
     private String address;
     private String city;
     private String state;
     private String phone;
     private String insurance;
     private String taxRemitted;
     private String permit;
     private String status;
     private int isDeleted;

    public VehicleDetails() {
    }

	
    public VehicleDetails(int isDeleted) {
        this.isDeleted = isDeleted;
    }
    public VehicleDetails(String vehicleNo, String vehicleCode, String noOfSeats, String maximumCapacity, String vehicleType, String address, String city, String state, String phone, String insurance, String taxRemitted, String permit, String status, int isDeleted) {
       this.vehicleNo = vehicleNo;
       this.vehicleCode = vehicleCode;
       this.noOfSeats = noOfSeats;
       this.maximumCapacity = maximumCapacity;
       this.vehicleType = vehicleType;
       this.address = address;
       this.city = city;
       this.state = state;
       this.phone = phone;
       this.insurance = insurance;
       this.taxRemitted = taxRemitted;
       this.permit = permit;
       this.status = status;
       this.isDeleted = isDeleted;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="vehicle_no", length=120)
    public String getVehicleNo() {
        return this.vehicleNo;
    }
    
    public void setVehicleNo(String vehicleNo) {
        this.vehicleNo = vehicleNo;
    }

    
    @Column(name="vehicle_code", length=120)
    public String getVehicleCode() {
        return this.vehicleCode;
    }
    
    public void setVehicleCode(String vehicleCode) {
        this.vehicleCode = vehicleCode;
    }

    
    @Column(name="no_of_seats", length=120)
    public String getNoOfSeats() {
        return this.noOfSeats;
    }
    
    public void setNoOfSeats(String noOfSeats) {
        this.noOfSeats = noOfSeats;
    }

    
    @Column(name="maximum_capacity", length=120)
    public String getMaximumCapacity() {
        return this.maximumCapacity;
    }
    
    public void setMaximumCapacity(String maximumCapacity) {
        this.maximumCapacity = maximumCapacity;
    }

    
    @Column(name="vehicle_type", length=120)
    public String getVehicleType() {
        return this.vehicleType;
    }
    
    public void setVehicleType(String vehicleType) {
        this.vehicleType = vehicleType;
    }

    
    @Column(name="address", length=120)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="city", length=120)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="state", length=120)
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }

    
    @Column(name="phone", length=120)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="insurance", length=120)
    public String getInsurance() {
        return this.insurance;
    }
    
    public void setInsurance(String insurance) {
        this.insurance = insurance;
    }

    
    @Column(name="tax_remitted", length=120)
    public String getTaxRemitted() {
        return this.taxRemitted;
    }
    
    public void setTaxRemitted(String taxRemitted) {
        this.taxRemitted = taxRemitted;
    }

    
    @Column(name="permit", length=120)
    public String getPermit() {
        return this.permit;
    }
    
    public void setPermit(String permit) {
        this.permit = permit;
    }

    
    @Column(name="status", length=120)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="is_deleted", nullable=false)
    public int getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(int isDeleted) {
        this.isDeleted = isDeleted;
    }




}


