package com.mx.itzamna.eschoolmx.model;
// Generated 12/04/2015 11:30:10 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Weekdays generated by hbm2java
 */
@Entity
@Table(name="weekdays"
    ,catalog="villaeducativa"
)
public class Weekdays  implements java.io.Serializable {


     private Integer id;
     private Integer batchId;
     private String weekday;

    public Weekdays() {
    }

    public Weekdays(Integer batchId, String weekday) {
       this.batchId = batchId;
       this.weekday = weekday;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="batch_id")
    public Integer getBatchId() {
        return this.batchId;
    }
    
    public void setBatchId(Integer batchId) {
        this.batchId = batchId;
    }

    
    @Column(name="weekday")
    public String getWeekday() {
        return this.weekday;
    }
    
    public void setWeekday(String weekday) {
        this.weekday = weekday;
    }




}


